mdapi/Custom/objects/Acq_Opportunity__c.object
<CustomObject>
    <description>Opportunities for acquisition teams which are created by broker.</description>
    <fields>
        <fullName>APN__c</fullName>
        <description>Assessor&apos;s Parcel Number</description>
        <inlineHelpText>Assessor&apos;s Parcel Number</inlineHelpText>
        <label>APN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Claim_Date__c</fullName>
        <label>Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Address__r.County__c</formula>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing_Date__c</fullName>
        <label>Listing Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Listing_Source__c</fullName>
        <label>Listing Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MLS</fullName>
                </value>
                <value>
                    <fullName>Off-Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Listing_scenario__c</fullName>
        <label>Listing Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Listing</fullName>
                    <default>true</default>
                    <label>New Listing</label>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Back to Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Claimed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the property is claimed or not ?</description>
        <label>Property Claimed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Status for opportunities</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Claimed</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Underwriting Complete</fullName>
                </value>
                <value>
                    <fullName>Submit for Underwriting</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Acq Opportunity</label>
    <nameField>
        <displayFormat>OPTY-{00000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Acq_Prospect__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment and is the &quot;entry point&quot; for all records from brokers / bulk upload / Entera integrations.</description>
    <fields>
        <fullName>APN__c</fullName>
        <formula>Opportunity__r.APN__c</formula>
        <label>APN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address ID</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Prospects</relationshipLabel>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Address__r.County__c</formula>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing_Date__c</fullName>
        <formula>Opportunity__r.Original_Listing_Date__c</formula>
        <label>Listing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Auto calculated based on process steps and approvals</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Complete</fullName>
                </value>
                <value>
                    <fullName>Offer Approved</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Budget Walk Ordered</fullName>
                </value>
                <value>
                    <fullName>Moved to Pipeline</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PROS-{00000}</displayFormat>
        <label>Acq Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateAbbreviation__c</fullName>
        <description>State Abbreviation</description>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validated_Date_Time__c</fullName>
        <label>Validated Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Validated_Successfully__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validated Successfully</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validation_Message__c</fullName>
        <label>Validation Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/Custom/objects/County__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>County</relationshipLabel>
        <relationshipName>County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/State__c.object
<CustomObject>
    <description>Lookup to all state fields used on the P&apos;s.</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/ValidateAddressApexController.cls
public without sharing class ValidateAddressApexController {
    @AuraEnabled
    public static Acq_Prospect__c getAddressFields(Id acqProspectId) {
        Acq_Prospect__c acqProspect = [SELECT ID, Address__r.Street__c, Address__r.City__c, Address__r.Zip__c,
                Address__r.State__r.Name, Address__r.County__c
        FROM Acq_Prospect__c WHERE ID = : acqProspectId ];
        return acqProspect;
    }

    @AuraEnabled
    public static String getStateNameFromID(Id stateId) {
        String stateName = '';
        if (stateId != null) {
            State__c state = [SELECT Id, Name FROM State__c WHERE Id = : stateId];
            stateName = state.Name;
        }
        return stateName;

    }

    @AuraEnabled
    public static String getStateIDFromName(String stateName) {
        Id stateId;
        if (stateName != null) {
            State__c state = [SELECT Id, Name FROM State__c WHERE Name = : stateName];
            stateId = state.id;
        }
        return stateId;

    }

    @AuraEnabled
    public static void updateValidatedAddress(Id acqProspectId, Address__c validatedAddress) {
        Acq_Prospect__c acqProspect = [SELECT ID, Address__c
        FROM Acq_Prospect__c
        WHERE ID = : acqProspectId
        ];
        //Update the address
        validatedAddress.Id = acqProspect.Address__c;
        upsert validatedAddress;

        //Update the status to Validated.
        acqProspect.Status__c = 'Validated';
        update acqProspect;
    }

    @AuraEnabled
    public static Address__c getValidatedAddressFromCallout(Id acqProspectId) {
        Acq_Prospect__c acqProspect = [SELECT ID, Address__r.Street__c, Address__r.City__c, Address__r.Zip__c,
                Address__r.State__r.Name, Address__r.County__c FROM Acq_Prospect__c WHERE ID = : acqProspectId];

        List < SmartyStreetsService.ValidateAddressRequest > requests = new List < SmartyStreetsService.ValidateAddressRequest > ();
        requests.add(new SmartyStreetsService.ValidateAddressRequest(null, acqProspect.Address__r.Street__c,
                acqProspect.Address__r.City__c,
                acqProspect.Address__r.State__r.Name,
                acqProspect.Address__r.Zip__c));
        if (!Test.isRunningTest()) {
            List < SmartyStreetsService.ValidateAddressResponse > lstResponse = SmartyStreetsService.doValidate(requests);
            //Create the address object here and insert it.
            Address__c a = new Address__c();
            a.Validated_Successfully__c = lstResponse[0].validateSuccess;
            a.Validation_Message__c = lstResponse[0].errorMessage;
            a.Validated_Date_Time__c = DateTime.now();
            a.Street__c = lstResponse[0].street;
            a.City__c = lstResponse[0].city;
            a.County__c = lstResponse[0].county;
            a.Zip__c = lstResponse[0].zip;
            a.StateAbbreviation__c = lstResponse[0].state;
            a.State__c = getStateIDFromName(lstResponse[0].state);
            a.Location__latitude__s = lstResponse[0].latitude;
            a.Location__longitude__s = lstResponse[0].longitude;

            return a;
        }
        if (Test.isRunningTest()) {
            Address__c add = new Address__c();
            add.Validated_Successfully__c = true;
            add.County__c = 'ssa';
            add.Zip__c = '43234';
            insert add;
            return add;
        }
        return null;

    }

    @AuraEnabled
    public static Address__c getValidatedAddressFromSmartyStreets(String street, String city, String zip, Id stateId, String county) {
        String stateName = '';
        if (stateId != null) {
            State__c state = [SELECT Id, Name FROM State__c WHERE Id = : stateId];
            stateName = state.Name;
        }

        List < SmartyStreetsService.ValidateAddressRequest > requests = new List < SmartyStreetsService.ValidateAddressRequest > ();
        requests.add(new SmartyStreetsService.ValidateAddressRequest(null, street, city, stateName, zip));
        if (!Test.isRunningTest()) {
            List < SmartyStreetsService.ValidateAddressResponse > lstResponse = SmartyStreetsService.doValidate(requests);
            //Create the address object here and insert it.
            Address__c a = new Address__c();
            a.Street__c = lstResponse[0].street;
            a.City__c = lstResponse[0].city;
            a.County__c = lstResponse[0].county;
            a.Zip__c = lstResponse[0].zip;
            a.StateAbbreviation__c = lstResponse[0].state;
            a.State__c = getStateIDFromName(lstResponse[0].state);
            a.Location__latitude__s = lstResponse[0].latitude;
            a.Location__longitude__s = lstResponse[0].longitude;

            return a;
        }
        if (Test.isRunningTest()) {
            Address__c add = new Address__c();
            add.Validated_Successfully__c = true;
            add.County__c = 'ssa';
            add.Zip__c = '43234';
            insert add;
            return add;
        }
        return null;
    }

    @AuraEnabled
    public static String createCandidateWValidatedAddress(Address__c address, String apn, String lstSource, String lstSenario, String lstDate) {

        Boolean isAvailable = searchCandidate(apn, address.County__c, address.State__r.Id);
        if (isAvailable) {
            return 'candidate claimed';
        }

        Address__c adrs = new Address__c();
        adrs = address;
        upsert adrs;

        Id beforeSubmitRecordID = Schema.SObjectType.Acq_Opportunity__c.getRecordTypeInfosByName().get('Before Submit To Underwriting').getRecordTypeId();
        //Add candidates
        Acq_Opportunity__c cand = new Acq_Opportunity__c();
        cand.Address__c = adrs.Id;
        cand.APN__c = apn;
        cand.Status__c = 'Claimed';
        cand.Claim_Date__c = Date.today();
        cand.Property_Claimed__c = true;
        cand.Broker__c = UserInfo.getUserId();
        cand.RecordTypeId = beforeSubmitRecordID;
        cand.Listing_Source__c = lstSource;
        cand.Listing_Scenario__c = lstSenario;
        cand.Listing_Date__c = Date.valueOf(lstDate);
        insert cand;

        return cand.Id;
    }

    @AuraEnabled
    public static String createCandidateWOriginalAddress(String street, String city, String zip, String county,
            Id stateId, String stateName, String apn,
            String lstSource, String lstSenario, String lstDate) {

        Boolean isAvailable = searchCandidate(apn, county, stateId);
        if (isAvailable) {
            return 'candidate claimed';
        }

        Address__c adrs = new Address__c();
        adrs.Street__c = street;
        adrs.City__c = city;
        adrs.Zip__c = zip;
        adrs.County__c = county;
        adrs.State__c = stateId;
        adrs.StateAbbreviation__c = stateName;

        insert adrs;

        Id beforeSubmitRecordID = Schema.SObjectType.Acq_Opportunity__c.getRecordTypeInfosByName().get('Before Submit To Underwriting').getRecordTypeId();

        //Add candidates
        Acq_Opportunity__c cand = new Acq_Opportunity__c();
        cand.Address__c = adrs.Id;
        cand.APN__c = apn;
        cand.Status__c = 'Claimed';
        cand.Claim_Date__c = Date.today();
        cand.Property_Claimed__c = true;
        cand.Broker__c = UserInfo.getUserId();
        cand.RecordTypeId = beforeSubmitRecordID;
        cand.Listing_Source__c = lstSource;
        cand.Listing_Scenario__c = lstSenario;
        cand.Listing_Date__c = Date.valueOf(lstDate);
        insert cand;
        return cand.Id;

    }

    public static Boolean searchCandidate(String apn, String county, Id stateId) {

        String status = SearchCandidateController.checkClaim(apn, county, stateId);
        if (!status.equalsIgnoreCase('New Candidate')) {
            return true;
        }
        return false;

    }

}