mdapi/Custom/objects/Acq_Budget_Walk__c.object
<CustomObject>
    <fields>
        <fullName>Cap_Rate_UW__c</fullName>
        <formula>IF(
					ISNULL(PipelineID__r.Cost_Basis_Est__c),
     Prospect_ID__r.Cap_Rate_UW__c,
					PipelineID__r.Cap_Rate_UW__c
					)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cap Rate @ UW</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cost_Basis_Est_UW__c</fullName>
        <formula>IF( 
				OR(
								ISBLANK(PipelineID__r.Cost_Basis_Est__c),ISNULL(PipelineID__r.Cost_Basis_Est__c)
				),
				Prospect_ID__r.Cost_Basis_Est_UW__c,
				PipelineID__r.Cost_Basis_Est__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Basis Est @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Monthly_Rent_UW__c</fullName>
        <formula>Prospect_ID__r.Expected_Gross_Monthly_Rent_UW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Gross Monthly Rent @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Rehab_Budget_Estimate__c</fullName>
        <formula>Prospect_ID__r.Initial_Rehab_Budget_Estimate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initial Rehab Budget Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Budget_Walks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pool__c</fullName>
        <formula>Prospect_ID__r.Pool__c</formula>
        <label>Pool</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prospect_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect ID</label>
        <referenceTo>Acq_Prospect__c</referenceTo>
        <relationshipName>Budget_Walks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ordered</fullName>
                    <default>true</default>
                    <label>Ordered</label>
                </value>
                <value>
                    <fullName>Walk Scheduled</fullName>
                </value>
                <value>
                    <fullName>Walk Complete</fullName>
                </value>
                <value>
                    <fullName>Budget Submitted</fullName>
                </value>
                <value>
                    <fullName>Budget Approved</fullName>
                </value>
                <value>
                    <fullName>Reduction Requested</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Acq Budget Walk</label>
    <nameField>
        <displayFormat>BW-{00000}</displayFormat>
        <label>Budget Walk ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Budget Walks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Acq_Prospect__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment and is the &quot;entry point&quot; for all records from brokers / bulk upload / Entera integrations.</description>
    <fields>
        <fullName>Annual_Insurance_Est_UW__c</fullName>
        <formula>Market__r.Insurance_Per_Home__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Insurance Est @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cap_Rate_UW__c</fullName>
        <formula>Pro_forma_NOI_UW__c / Cost_Basis_Est_UW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cap Rate @ UW</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Capitalized_Acq_Costs_Estimate__c</fullName>
        <formula>Market__r.Capitalized_Acq_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Capitalized Acq Costs Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Closing_Title_Acq_Cost_Est__c</fullName>
        <label>Closing/Title/Acq Cost Est</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Basis_Discount_to_MV__c</fullName>
        <formula>1 - Cost_Basis_as_of_MV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Basis Discount to MV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cost_Basis_Est_UW__c</fullName>
        <formula>Purchase_Price__c + Initial_Rehab_Budget_Estimate__c  + Closing_Title_Acq_Cost_Est__c + Capitalized_Acq_Costs_Estimate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Basis Est @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Basis_as_of_MV__c</fullName>
        <formula>Cost_Basis_Est_UW__c / Market_Value_UW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Basis as % of MV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Effective_Gross_Income_UW__c</fullName>
        <formula>Total_Revenue_UW__c + Fixed_Expenses_Inc_Pool_UW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective Gross Income @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Monthly_Rent_UW__c</fullName>
        <label>Expected Gross Monthly Rent @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fixed_Expenses_Inc_Pool_UW__c</fullName>
        <formula>-1*(Property_Tax_Est_UW__c + (Monthly_HOA_UW__c *12) + Annual_Insurance_Est_UW__c+ IF(Pool__c=TRUE,  Market__r.Pool_Exp_Per_Home__c , 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fixed Expenses (Inc. Pool) @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Rehab_Budget_Estimate__c</fullName>
        <label>Initial Rehab Budget Estimate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market_Value_UW__c</fullName>
        <label>Market Value @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_HOA_UW__c</fullName>
        <label>Monthly HOA @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pool__c</fullName>
        <formula>Opportunity__r.Pool__c</formula>
        <label>Pool</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pro_forma_NOI_UW__c</fullName>
        <formula>Effective_Gross_Income_UW__c + Controllable_Expenses_UW__c + Direct_Shared_Services_UW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pro-forma NOI @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Tax_Est_UW__c</fullName>
        <label>Property Tax Est. @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <formula>IF(
				ISBLANK(Approved_Offer_Price__c),
				Offer_Price_Max_Bid__c ,
				IF(
								ISBLANK(Offer_Price_Max_Bid__c),
								0,
								Approved_Offer_Price__c
				)
)</formula>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Auto calculated based on process steps and approvals</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Complete</fullName>
                </value>
                <value>
                    <fullName>Offer Approved</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Budget Walk Ordered</fullName>
                </value>
                <value>
                    <fullName>Moved to Pipeline</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Revenue_UW__c</fullName>
        <formula>Rental_Income_UW__c  +  Other_Inc_Conc_Bad_Debt_UW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Revenue @ UW</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PROS-{00000}</displayFormat>
        <label>Acq Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <fields>
        <fullName>Control_Pool_Exp__c</fullName>
        <label>Control-Pool Exp %</label>
        <precision>12</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Direct_SSA_Per_Home__c</fullName>
        <label>Direct SSA Per Home</label>
        <precision>16</precision>
        <scale>10</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OI_Conc_BD_as_of_RI__c</fullName>
        <label>OI/Conc/BD as % of RI</label>
        <precision>12</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Occupancy__c</fullName>
        <description>Occupancy based on market</description>
        <label>Occupancy</label>
        <precision>10</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pool_Exp_Per_Home__c</fullName>
        <label>Pool Exp Per Home</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/reductionCalculatorCtrler.cls
/*******************************************************************************************************
 * Name             : reductionCalculator
 * Created By       : SEKAR RAJ
 * Created Date     : Apr 09,2018
 * Purpose          : TO calculate reduction Amount and update relevant prospect  
 * Version			: 1.0 - SEKAR RAJ  
 					  1.1 - SEKAR RAJ -- Updated Prospect and Calclating Reduction Amount                     
***********************************************************************************************************/
public class reductionCalculatorCtrler {
    
/***********************************************************************************
  Method to Calculate Reduction
************************************************************************************/
    @auraEnabled
    public static Acq_Prospect__c getProspectValues(String recordId
                                              ){
        Acq_Budget_Walk__c acqBud = [SELECT id,Name,Prospect_ID__c from Acq_Budget_Walk__c where id=:recordId ];
                                                  
        Acq_Prospect__c acqProsData = [SELECT id,Name,Purchase_Price__c,Initial_Rehab_Budget_Estimate__c,
                                   Closing_Title_Acq_Cost_Est__c,Capitalized_Acq_Costs_Estimate__c,Total_Revenue_UW__c,
                                   Fixed_Expenses_Inc_Pool_UW__c,Market__r.Control_Pool_Exp__c,Market__r.Direct_SSA_Per_Home__c,
                                   Pro_forma_NOI_UW__c ,Cost_Basis_Est_UW__c,Market_Value_UW__c,Cap_Rate_UW__c, Expected_Gross_Monthly_Rent_UW__c,
                                   Property_Tax_Est_UW__c, Monthly_HOA_UW__c,Cost_Basis_as_of_MV__c,Cost_Basis_Discount_to_MV__c,Effective_Gross_Income_UW__c
                                   from Acq_Prospect__c where Id=:acqBud.Prospect_ID__c];   
         
       return acqProsData;
    }
    
    @auraEnabled
    public static Acq_Prospect__c calcReduction(String recordId){
        Acq_Budget_Walk__c acqBud = [SELECT id,Name,Prospect_ID__c from Acq_Budget_Walk__c where id=:recordId ];
                                                  
        Acq_Prospect__c acqPros = [SELECT id,Name,Purchase_Price__c,Initial_Rehab_Budget_Estimate__c,
                                   Closing_Title_Acq_Cost_Est__c,Capitalized_Acq_Costs_Estimate__c,Total_Revenue_UW__c,
                                   Fixed_Expenses_Inc_Pool_UW__c,Market__r.Control_Pool_Exp__c,Market__r.Direct_SSA_Per_Home__c,
                                   Pro_forma_NOI_UW__c ,Cost_Basis_Est_UW__c,Market_Value_UW__c,Cap_Rate_UW__c,Market__r.Occupancy__c,
                                   Market__r.OI_Conc_BD_as_of_RI__c,Annual_Insurance_Est_UW__c,Market__r.Pool_Exp_Per_Home__c,Pool__c
                                   from Acq_Prospect__c where Id=:acqBud.Prospect_ID__c];   
         
       return acqPros;
    }
    
    @auraEnabled
    public static String updateProspect(Integer marketValue,Integer expGrsMon,Integer propTaxEst,Integer monHoaDet,String recordId){
        Acq_Budget_Walk__c acqBud = [SELECT id,Name,Prospect_ID__c,Prospect_ID__r.Status__c from Acq_Budget_Walk__c where id=:recordId];
        Acq_Prospect__c updatePros = new Acq_Prospect__c(
        		Id=acqBud.Prospect_ID__c
        );
        
        updatePros.Market_Value_UW__c = Integer.valueOf(marketValue);
        updatePros.Expected_Gross_Monthly_Rent_UW__c  = Integer.valueOf(expGrsMon);
        updatePros.Property_Tax_Est_UW__c  = Integer.valueOf(propTaxEst);
        updatePros.Monthly_HOA_UW__c = Integer.valueOf(monHoaDet);
        try{
            if(acqBud.Prospect_ID__r.Status__c == 'Cancelled / Dead'){
                return acqBud.Prospect_ID__r.Status__c;
            } else{
                update updatePros;
            	return acqBud.Prospect_ID__r.Status__c;
            }
        	
        }catch(DMLException de){
            System.debug('Error>>>'+ de.getLineNumber()+'>>> '+de.getMessage());
        }                       
        return null;
    }
    
}