mdapi/Custom/objects/Acq_Opportunity__c.object
<CustomObject>
    <description>Opportunities for acquisition teams which are created by broker.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market2__c</fullName>
        <description>This is entered to accommodate the downstream requirements</description>
        <label>Market2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submarket__c</fullName>
        <description>Auto filled based on Zip code entered</description>
        <label>Submarket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Acq Opportunity</label>
    <nameField>
        <displayFormat>OPTY-{00000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Zip_code_reference__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Get the market, submarket and Location score from zip code</description>
    <fields>
        <fullName>LocationScore__c</fullName>
        <label>LocationScore</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market2__c</fullName>
        <label>Market2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubMarket__c</fullName>
        <label>SubMarket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zip Code Reference</label>
</CustomObject>

mdapi/Custom/classes/AcqOpportunityTriggerHelper.cls
public without sharing class AcqOpportunityTriggerHelper {
    public static void addMarketFromAddress(List<Acq_Opportunity__c> acqOpportunities) {
        //Get the region Map against a Region Name
        Map<String,Region__c> allRegionsByStrings = new Map<String, Region__c>();
        for(Region__c region : [SELECT Id, Name FROM Region__c]) {
            allRegionsByStrings.put(region.Name,region);
        }
        System.debug('All regions by String ' + allRegionsByStrings);
        System.debug('Trigger.new is ' + acqOpportunities);

        //All address in a set
        Set<Id> allAddressIds = new Set<Id>();
        for(Acq_Opportunity__c opp : acqOpportunities) {
            if(opp.Address__c != null) {
                allAddressIds.add(opp.Address__c);
            }
        }

        List<Address__c> allAddresses = [SELECT Id, Zip__c FROM Address__c WHERE Id in :allAddressIds];
        //Get all Zip values to filter from custom setting
        Map<Id,String> allZipMapIds = new Map<Id, String>();
        for(Address__c address : allAddresses) {
            allZipMapIds.put(address.Id, address.Zip__c);
        }
        System.debug('All Id to Zip for opp ' + allZipMapIds);


        Map<String, Zip_code_reference__c> zipCodeReferenceMap = new Map<String, Zip_code_reference__c>();
        for(Zip_code_reference__c zip : [SELECT Name, Zip__c, Market__c, Market2__c, LocationScore__c, SubMarket__c
        FROM Zip_code_reference__c WHERE Name in :allZipMapIds.values()]) {
            zipCodeReferenceMap.put(zip.Name, zip);
        }
        System.debug('Zip code Reference Map ' + zipCodeReferenceMap);

        for(Acq_Opportunity__c opp : acqOpportunities) {
            if(opp.Address__c != null){
                System.debug('Zip code from address ' + opp.Address__r.zip__c);
                Zip_code_reference__c zipCodeReference = zipCodeReferenceMap.get(allZipMapIds.get(opp.Address__c));
                if(zipCodeReference != null){
                    System.debug('zipCodeReference.Market__c gives ' + zipCodeReference.Market__c);
                    Region__c region = allRegionsByStrings.get(zipCodeReference.Market__c);
                    if(region != null)
                    {
                        opp.Market__c = region.Id;
                    }
                    opp.Market2__c = zipCodeReference.Market2__c;
                    opp.Submarket__c = zipCodeReference.SubMarket__c;
                }

            }

        }
    }
    
}