mdapi/Custom/objects/Acq_Opportunity__c.object
<CustomObject>
    <description>Opportunities for acquisition teams which are created by broker.</description>
    <fields>
        <fullName>APN__c</fullName>
        <description>Assessor&apos;s Parcel Number</description>
        <inlineHelpText>Assessor&apos;s Parcel Number</inlineHelpText>
        <label>APN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bid_Type__c</fullName>
        <label>Offer Type (Bid Type)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Sale</fullName>
                    <default>true</default>
                    <label>Standard Sale</label>
                </value>
                <value>
                    <fullName>REO</fullName>
                </value>
                <value>
                    <fullName>Short Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IMG_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMG Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IMG_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMG Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market2__c</fullName>
        <description>This is entered to accommodate the downstream requirements</description>
        <label>Market2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single Family Home</fullName>
                    <default>true</default>
                    <label>Single Family Home</label>
                </value>
                <value>
                    <fullName>Townhome</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>Duplex</fullName>
                </value>
                <value>
                    <fullName>Triplex</fullName>
                </value>
                <value>
                    <fullName>Quad</fullName>
                </value>
                <value>
                    <fullName>Vacant Land</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submarket__c</fullName>
        <description>Auto filled based on Zip code entered</description>
        <label>Submarket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Acq Opportunity</label>
    <nameField>
        <displayFormat>OPTY-{00000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Acq_Prospect__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment and is the &quot;entry point&quot; for all records from brokers / bulk upload / Entera integrations.</description>
    <fields>
        <fullName>APN__c</fullName>
        <formula>Opportunity__r.APN__c</formula>
        <label>APN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bid_Type__c</fullName>
        <label>Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Sale</fullName>
                </value>
                <value>
                    <fullName>REO</fullName>
                </value>
                <value>
                    <fullName>Short Sale</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Bulk Sale</fullName>
                </value>
                <value>
                    <fullName>New Build</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IMG_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default to market based assignment but can be changed if needed</description>
        <label>Analyst IMG</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IMG_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default to market based assignment but can be changed if needed</description>
        <label>Director IMG</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Prospects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <formula>Text(Opportunity__r.Property_Type__c)</formula>
        <label>Property Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVP_IMG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SVP IMG</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Prospects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submarket__c</fullName>
        <label>Submarket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PROS-{00000}</displayFormat>
        <label>Acq Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/AcquisitionIQ__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>AcquisitionIQ</label>
</CustomObject>

mdapi/Custom/objects/County__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>County</relationshipLabel>
        <relationshipName>County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <fields>
        <fullName>IMG_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMG Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IMG_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMG Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVP_IMG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SVP IMG</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/Custom/objects/Zip_code_reference__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Get the market, submarket and Location score from zip code</description>
    <fields>
        <fullName>LocationScore__c</fullName>
        <label>LocationScore</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market2__c</fullName>
        <label>Market2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubMarket__c</fullName>
        <label>SubMarket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zip Code Reference</label>
</CustomObject>

Custom--app/main/default/classes/createOppController.cls
public without sharing class createOppController {
    public class IntegException extends Exception {}
    @AuraEnabled
    public static String createOpportunity(String csvdata){
     	String res ='';
      try{ 
        AcqCSVResponseHandler csvResponseHandler = new AcqCSVResponseHandler();
		csvResponseHandler = (AcqCSVResponseHandler) System.JSON.deserialize(csvdata, AcqCSVResponseHandler.class);
       
        // To Fetch the State Id
                Map<String,String> nameVsIdState;
                nameVsIdState = new Map<String,String>();
                for(State__c st : [SELECT id,Name From State__c]){
                    if(!nameVsIdState.containsKey(st.Name)){
                        nameVsIdState.put(st.Name, st.Id);
                    }
                }
            
           // To Fetch the Zip Code Details
                Map<String, Zip_code_reference__c> zipCodeReferenceMap = new Map<String, Zip_code_reference__c>();
                for(Zip_code_reference__c zip : [SELECT Name, Zip__c, Market__c,Market2__c, LocationScore__c, SubMarket__c
                                                 FROM Zip_code_reference__c]) {
                                                     zipCodeReferenceMap.put(zip.Name, zip);
                                                 }
               
                
        	//Get the region Map against a Region Name
                Map<String,Region__c> allRegionsByStrings = new Map<String, Region__c>();
                for(Region__c region : [SELECT Id, Name, IMG_Director__c, IMG_Analyst__c, SVP_IMG__c FROM Region__c]) {
                    allRegionsByStrings.put(region.Name,region);
                }
          // Get Broker IQ id
          List<AcquisitionIQ__c> customUser = [SELECT id,Name,User_Name__c from AcquisitionIQ__c];
           
          Map<String,String> brokUserId  = new Map<String,String>();
            
         
            for(User userId :[SELECT id,Name,Username  from User]){
                if(!brokUserId.containsKey(userId.Username)){
                    brokUserId.put(userId.Username ,userId.Id);
                }
                
            }
          //string userName = brokUserId.get(customUser[0].User_Name__c);
           string userName = UserInfo.getUserId();
           Map<String,String> alloppres = new Map<String,String>();
            
            for(Acq_Opportunity__c oppList : [SELECT Id,Name,APN__c from Acq_Opportunity__c]){
                if(!alloppres.containsKey(oppList.APN__c)){
                	alloppres.put(oppList.APN__c,oppList.APN__c);
                }
            }
          
          // Duplicate APN Check
           string apn = csvResponseHandler.APN;
            if(apn.contains(' ')){
                  csvResponseHandler.APN =apn.replaceAll( '\\s+','');
              }
			else if(Apn.contains('-')){
                   csvResponseHandler.APN =apn.replaceAll( '-','');
            }
            else if(Apn.contains('.')){
                   csvResponseHandler.APN =apn.replaceAll('\\.', '');
            }
            else{
                   csvResponseHandler.APN = apn;                               
			} 
          
            if((alloppres.get(csvResponseHandler.APN)) == (csvResponseHandler.APN)){
            	throw new IntegException('APNexception');
            }
          	if((zipCodeReferenceMap.get(csvResponseHandler.Property_Zip_Code)) == null){
            	throw new IntegException('ZIPexception');
            }
      
           Acq_Prospect__c prosId =  csvUploadCtrler.insertOppandProsRecords(csvResponseHandler,nameVsIdState,zipCodeReferenceMap,allRegionsByStrings,
                                                              userName,alloppres);
     	  
          String recId = prosId.Id;
          
          res = recId;
          
      }  catch(IntegException Exp){
           
            //Add custom error code when you could not insert a record
            if(Exp.getMessage() == 'APNexception'){
                 res = 'Duplicate APN cannot be inserted';
            } 
            if(Exp.getMessage() == 'ZIPexception') {
                res = 'ERROR';
            }
        }
        catch(Exception e){
            system.debug(e.getMessage());
            res = e.getMessage();
            //res = 'ERROR';
            
            
      }
      	system.debug(res);
          return res;
    }
    @AuraEnabled
    public static List<String> getPicklistValues(String fieldName){
        List<String> PickValues = new List<String>();
        Schema.DescribeFieldResult fieldResult;
        List<Schema.PicklistEntry> outputs;
        if(fieldName == 'Property_Type__c') {
           fieldResult = Acq_Opportunity__c.Property_Type__c.getDescribe();
           
        }
        if(fieldName == 'Bid_Type__c') {
           fieldResult = Acq_Prospect__c.Bid_Type__c.getDescribe();
           
        }
        if(fieldName == 'Parking__c') {
           fieldResult = Acq_Opportunity__c.Parking__c.getDescribe();
           
        }
        if(fieldName == 'Roof_Type__c') {
           fieldResult = Acq_Opportunity__c.Roof_Type__c.getDescribe();
           
        }
        if(fieldName == 'HVAC_Type__c') {
           fieldResult = Acq_Opportunity__c.HVAC_Type__c.getDescribe();
           
        }
        if(fieldName == 'HOA__c') {
           fieldResult = Acq_Opportunity__c.HOA__c.getDescribe();
           
        }
        if(fieldName == 'RPC_Structure_Quality__c') {
           fieldResult = Acq_Prospect__c.RPC_Structure_Quality__c.getDescribe();
           
        }
        
           outputs = fieldResult.getPicklistValues();
           for(Schema.PicklistEntry fout:outputs){
           PickValues.add(fout.getLabel());
        	}
        
         
        return PickValues;
    }
    @AuraEnabled 
    public static List<State__c> getState(){
        return[select id,Name  from State__c];
    }
    @AuraEnabled 
    public static List<County__c > getCounty(String state){
        return[select id,Name,State__r.Name from County__c where State__r.Name=:state];
    }
    
}