mdapi/Custom/objects/Acq_Budget_Walk__c.object
<CustomObject>
    <fields>
        <fullName>PipelineID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline ID</label>
        <referenceTo>AcqPipeline__c</referenceTo>
        <relationshipLabel>Acq Budget Walks</relationshipLabel>
        <relationshipName>Budget_Walks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect ID</label>
        <referenceTo>Acq_Prospect__c</referenceTo>
        <relationshipName>Budget_Walks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Acq Budget Walk</label>
    <nameField>
        <displayFormat>BW-{00000}</displayFormat>
        <label>Budget Walk ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Budget Walks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/AcqPipeline__c.object
<CustomObject>
    <fields>
        <fullName>Prospect_Record__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Prospect Record</label>
        <referenceTo>Acq_Prospect__c</referenceTo>
        <relationshipName>Pipeline</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>doOrderBudgetWalk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>doOrderBudgetWalk</label>
        <type>Checkbox</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <displayFormat>PIPE-{00000}</displayFormat>
        <label>Pipeline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/classes/TriggerAcqPipelineHelper.cls
public with sharing class TriggerAcqPipelineHelper {
    
     public static void updateBudWalk(List<AcqPipeline__c> acqPipe){
         
        List<Acq_Budget_Walk__c> budgetWalkToUpdate = new List<Acq_Budget_Walk__c>();
        List<Id> listIds = new List<Id>();
        for(AcqPipeline__c pipeRecId : acqPipe){
            listIds.add(pipeRecId.Prospect_Record__c);
        }
        List<Acq_Budget_Walk__c> budgetWalks = [SELECT ID FROM Acq_Budget_Walk__c 
                                                        WHERE Prospect_ID__c IN : listIds];
        for(AcqPipeline__c pipelineRecord : acqPipe) {
            if(pipelineRecord.doOrderBudgetWalk__c == true) {
                //Check if Budget walk is not already associated with it.
                //Get budget walk record associated with Prospect
                if(budgetWalks.size() > 0) {
                 for(Acq_Budget_Walk__c b1 : budgetWalks) {
                       b1.PipelineID__c = pipelineRecord.ID;
                            budgetWalkToUpdate.add(b1);
                   }
                }
            }
        }
        
        update budgetWalkToUpdate;
             
     }

}