mdapi/Custom/objects/Acq_Opportunity__c.object
<CustomObject>
    <description>Opportunities for acquisition teams which are created by broker.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker_Offer_Price__c</fullName>
        <label>Broker Requested Offer Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Broker_Offer_Status__c</fullName>
        <description>Offer status</description>
        <label>Broker Offer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IH Director Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Seller</fullName>
                </value>
                <value>
                    <fullName>Counteroffer</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Director_IMG_Offer_Approval_Date__c</fullName>
        <description>To be populated automatically when offer is made</description>
        <label>Director IMG Offer Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IMG_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMG Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IMG_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMG Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Price__c</fullName>
        <description>To be populated automatically when offer is made</description>
        <label>Approved Offer Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Status for opportunities</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Claimed</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Underwriting Complete</fullName>
                </value>
                <value>
                    <fullName>Submit for Underwriting</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Acq Opportunity</label>
    <nameField>
        <displayFormat>OPTY-{00000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Acq_Prospect__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment and is the &quot;entry point&quot; for all records from brokers / bulk upload / Entera integrations.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address ID</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Prospects</relationshipLabel>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Offer_Price__c</fullName>
        <label>Approved Offer Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Broker_Offer_Status__c</fullName>
        <formula>Text(Opportunity__r.Broker_Offer_Status__c)</formula>
        <label>Broker Offer Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director_IMG_Offer_Approval_Date__c</fullName>
        <label>Director IMG Offer Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IMG_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default to market based assignment but can be changed if needed</description>
        <label>Analyst IMG</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IMG_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default to market based assignment but can be changed if needed</description>
        <label>Director IMG</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acq_Prospects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Score__c</fullName>
        <label>Location Score</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity ID</label>
        <referenceTo>Acq_Opportunity__c</referenceTo>
        <relationshipLabel>Prospects</relationshipLabel>
        <relationshipName>Acq_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Auto calculated based on process steps and approvals</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Complete</fullName>
                </value>
                <value>
                    <fullName>Offer Approved</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Budget Walk Ordered</fullName>
                </value>
                <value>
                    <fullName>Moved to Pipeline</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PROS-{00000}</displayFormat>
        <label>Acq Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/Custom/objects/Zip_code_reference__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Get the market, submarket and Location score from zip code</description>
    <fields>
        <fullName>LocationScore__c</fullName>
        <label>LocationScore</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zip Code Reference</label>
</CustomObject>

Custom--app/main/default/classes/AcqProspectTriggerHelper.cls
public without sharing class AcqProspectTriggerHelper {
    
    public static void updateOpportuniyStatus(List<Acq_Prospect__c> acqPros){
        
        List<Id> listIds = new List<Id>();
        for (Acq_Prospect__c childObj : acqPros) {
            listIds.add(childObj.Id);
         }
        List<Acq_Opportunity__c> oppListToUpdate  = new List<Acq_Opportunity__c>();
        for(Acq_Prospect__c pros : [SELECT Id, Status__c, name,IMG_Analyst__r.Id,IMG_Director__r.Id, Approved_Offer_Price__c,Director_IMG_Offer_Approval_Date__c,Opportunity__r.Name, Opportunity__r.Id from Acq_Prospect__c where Id IN : listIds]){
            if(pros.Status__c == 'Offer Approved'){
                Acq_Opportunity__c opp = new Acq_Opportunity__c(Id = pros.Opportunity__r.Id);
                opp.Broker_Offer_Status__c = 'IH Director Approved';
                opp.Broker_Offer_Price__c = pros.Approved_Offer_Price__c;
                opp.Offer_Price__c = pros.Approved_Offer_Price__c;
                opp.Director_IMG_Offer_Approval_Date__c = pros.Director_IMG_Offer_Approval_Date__c;
                opp.IMG_Analyst__c = pros.IMG_Analyst__r.Id;
                opp.IMG_Director__c = pros.IMG_Director__r.Id;
                oppListToUpdate.add(opp);
                
            }
    	}
        
        if(oppListToUpdate.size() > 0){
            update oppListToUpdate;
        }
 	}
    
    @InvocableMethod
    public static void updateLocationScore(List<ID> acqProsIDs) {
        Map<String, Decimal> locationScoreMap = new Map<String, Decimal>();
        for(Zip_code_reference__c score : Zip_code_reference__c.getAll().values())
        {
             locationScoreMap.put(score.Name , score.LocationScore__c);
        }
        List<Acq_Prospect__c> prospects = [SELECT ID, Address__r.Zip__c FROM Acq_Prospect__c WHERE ID in :acqProsIDs];
        for(Acq_Prospect__c prospect : prospects) {
            System.debug('Property Zip ' + prospect.Address__r.Zip__c);
            System.debug('Score is ' + locationScoreMap.get(prospect.Address__r.Zip__c));
            prospect.Location_Score__c = locationScoreMap.get(prospect.Address__r.Zip__c);            
        }
        update prospects;
        System.debug('Prospects after ' + prospects);
    }
    

}