mdapi/Custom/objects/Acq_Opportunity__c.object
<CustomObject>
    <description>Opportunities for acquisition teams which are created by broker.</description>
    <fields>
        <fullName>APN__c</fullName>
        <description>Assessor&apos;s Parcel Number</description>
        <inlineHelpText>Assessor&apos;s Parcel Number</inlineHelpText>
        <label>APN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Address__r.County__c</formula>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Claimed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the property is claimed or not ?</description>
        <label>Property Claimed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_APN__c</fullName>
        <description>Unique APN</description>
        <formula>APN__c &amp; &apos;-&apos; &amp; Address__r.County__c &amp; &apos;-&apos; &amp; Address__r.State__r.Name</formula>
        <label>Unique APN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Status for opportunities</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Claimed</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Underwriting Complete</fullName>
                </value>
                <value>
                    <fullName>Submit for Underwriting</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Acq Opportunity</label>
    <nameField>
        <displayFormat>OPTY-{00000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acq Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/County__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>County</relationshipLabel>
        <relationshipName>County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <fields>
        <fullName>Active_Claims_per_Broker__c</fullName>
        <defaultValue>20</defaultValue>
        <description>Number of active claims per broker</description>
        <label>Active Claims per Broker</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/State__c.object
<CustomObject>
    <description>Lookup to all state fields used on the P&apos;s.</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Custom--app/main/default/classes/SearchCandidateController.cls
public without sharing class SearchCandidateController {
	@AuraEnabled
    public static String checkClaim(String apn, String county, Id state) {
        //Null check
        system.debug(apn+county+state);
        List<Acq_Opportunity__c> candidates;
        State__c s;
        String status;
        String uniqueApn;
        if(county != '' && state != null) {
            s = [SELECT Name FROM State__c WHERE Id = :state];
            if(s != null){
                uniqueApn = apn + '-' + county + '-' + s.Name;
            } else {
                uniqueApn = apn + '-' + county;
            }
            candidates = [SELECT ID, Property_Claimed__c
                        FROM Acq_Opportunity__c
                        WHERE Unique_APN__c = :uniqueApn];

        } else {
            candidates = [SELECT ID, Property_Claimed__c
                        FROM Acq_Opportunity__c
                        WHERE APN__c =:apn];
        }


        if(candidates.size() > 1) {
            //More candidate with same APN, county and state
            //status = 'More than 1 candidate';
            status = 'No County OR State';
        } else if(candidates.size() == 1) {
            for(Acq_Opportunity__c c : candidates){
                If(c.Property_Claimed__c == false){
              		status = 'Claim Candidate'; //Allow to claim candidate - Claim candidate
				} else if (c.Property_Claimed__c == true) {
					status = 'Candidate Claimed'; //Sorry you cannot claim the property - toast
				} 
            } 
        } else {
            //Create a new Candidate
            status = 'New Candidate';
        }
        
        return status;
        
    }
    
    @AuraEnabled
    public static Boolean checkActiveClaimsByUser() {
        //Check active claims per broker
        Integer countClaims = [SELECT count() 
                                FROM Acq_Opportunity__c 
                                WHERE Broker__c =:UserInfo.getUserId() 
                                AND status__c in ('New','Claimed','Working')];
        System.debug('Active claims are' + countClaims);
        //Get the User region
        User u = [SELECT ID, Region__c FROM User WHERE id = :UserInfo.getUserID()];
        //Market Active_Claims_per_Broker__c
        Region__c reg = [SELECT ID, Active_Claims_per_Broker__c FROM Region__c WHERE Name = :u.Region__c];
        if(countClaims >= reg.Active_Claims_per_Broker__c) {
            return true;
        } else {
            return false;
        }  
    }
    
    @AuraEnabled 
    public static List<State__c> getState(){
        return[select id,Name  from State__c order by Name];
    }
    
    @AuraEnabled 
    public static State__c getStateId(String StateName){
        return[select id from State__c where Name=:StateName];
    }
    
    
   @AuraEnabled 
    public static List<County__c > getCounty(String state){
        return[select id,Name,State__r.Name from County__c where State__r.Name=:state order by Name];
    }
   
    @AuraEnabled
    public static String getURLName(){
        String host = URL.getSalesforceBaseUrl().getHost();
        return host;
    }
    
}