mdapi/Custom/objects/AcqPipeline__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Rejected_Date__c</fullName>
        <label>Approved/Rejected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Broker_Offer_Status__c</fullName>
        <formula>Text(Opportunity__r.Broker_Offer_Status__c)</formula>
        <label>Broker Offer Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_Statement_Contract_Price__c</fullName>
        <label>Closing Contract Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Closing_Statement_Funds_Due_from_Buyer__c</fullName>
        <label>Closing COE Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Complete_Address__c</fullName>
        <formula>Address__r.Street__c &amp;&apos;, &apos;&amp; Address__r.City__c &amp;&apos;, &apos;&amp; IF(Address__r.State__r.Name = &apos;&apos;, &apos;&apos;, Address__r.State__r.Name &amp;&apos;, &apos;) &amp; Address__r.Zip__c</formula>
        <label>Complete Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <formula>Address__r.County__c</formula>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PipeToPortFolio_Status__c</fullName>
        <label>PipeToPortFolio Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pipeline_Status__c</fullName>
        <label>Pipeline Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Reviewed</fullName>
                </value>
                <value>
                    <fullName>Review Complete</fullName>
                </value>
                <value>
                    <fullName>Due Diligence Approved</fullName>
                </value>
                <value>
                    <fullName>Closing Approved</fullName>
                </value>
                <value>
                    <fullName>Moved to Queue</fullName>
                </value>
                <value>
                    <fullName>Portfolio Created</fullName>
                </value>
                <value>
                    <fullName>Cancelled/Dead</fullName>
                </value>
                <value>
                    <fullName>Closed/Dead</fullName>
                    <isActive>false</isActive>
                    <label>Closed/Dead</label>
                </value>
                <value>
                    <fullName>Order COE</fullName>
                    <isActive>false</isActive>
                    <label>Order COE</label>
                </value>
                <value>
                    <fullName>Rehab approved</fullName>
                    <isActive>false</isActive>
                    <label>Rehab approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <displayFormat>PIPE-{00000}</displayFormat>
        <label>Pipeline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/County__c.object
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/PipelinAppListCtrler.cls
/*
Resource : SEKAR RAJ
Date : Feb 7 2018
Description : 
*/

public with sharing class PipelinAppListCtrler {

    // Initialize the wrapper object
    public List<wrapPipeline> wrapperPipList{get;set;}
    
    public List<AcqPipeline__c> selectedPipList{get;set;}
    public List<AcqPipeline__c> appRejPipeList{get;set;}
    
     public PipelinAppListCtrler(ApexPages.StandardController controller) {
        wrapperPipList = new List<wrapPipeline>();
        for(AcqPipeline__c pipe: [select Id, Name,Broker_Offer_Status__c,Closing_Statement_Contract_Price__c,Closing_Statement_Funds_Due_from_Buyer__c,Complete_Address__c,PipeToPortFolio_Status__c,Approved_Rejected_Date__c,County__c from AcqPipeline__c where Pipeline_Status__c ='Moved to Queue' and PipeToPortFolio_Status__c !='Approved' and PipeToPortFolio_Status__c !='Rejected']){
            if(Test.isRunningTest()){
                wrapPipeline wrpClass = new wrapPipeline(pipe);
                wrpClass.selected = true;
                wrapperPipList.add(wrpClass);
            }else{
                wrapperPipList.add(new wrapPipeline(pipe));
            }
			system.debug(wrapperPipList);
        }
         appRejPipeList = [select Id, Name,Broker_Offer_Status__c,PipeToPortFolio_Status__c,Approved_Rejected_Date__c,Closing_Statement_Contract_Price__c,Closing_Statement_Funds_Due_from_Buyer__c from AcqPipeline__c where PipeToPortFolio_Status__c IN('Approved','Rejected') and Pipeline_Status__c ='Moved to Queue'];
    }
    
    public PageReference ProcessApproved(){
        selectedPipList = new List<AcqPipeline__c>();
        for(wrapPipeline wrapAc : wrapperPipList){
            if(wrapAc.selected == true){
                selectedPipList.add(wrapAc.PipLin);
            }
        }
        List<AcqPipeline__c> pipListToUpdate  = new List<AcqPipeline__c>();
        for(AcqPipeline__c approvePipe:selectedPipList){
            AcqPipeline__c pipLineUp = new AcqPipeline__c(id = approvePipe.Id);
            pipLineUp.PipeToPortFolio_Status__c = 'Approved';
            pipLineUp.Approved_Rejected_Date__c = Date.today();
            pipListToUpdate.add(pipLineUp);
        }
        
        if(pipListToUpdate.size()>0){
            update pipListToUpdate;
        }
       PageReference p=new Pagereference('/apex/PipelnAppList');
       p.setRedirect(true);
       return p;

    }
    
    public Pagereference ProcessRejected(){
        selectedPipList = new List<AcqPipeline__c>();
        for(wrapPipeline wrapAc : wrapperPipList){
            if(wrapAc.selected == true){
                selectedPipList.add(wrapAc.PipLin);
            }
        }
        List<AcqPipeline__c> pipListToUpdate  = new List<AcqPipeline__c>();
        for(AcqPipeline__c approvePipe:selectedPipList){
            AcqPipeline__c pipLineUp = new AcqPipeline__c(id = approvePipe.Id);
            pipLineUp.PipeToPortFolio_Status__c = 'Rejected';
            pipLineUp.Approved_Rejected_Date__c = Date.today();
            pipListToUpdate.add(pipLineUp);
        }
        if(pipListToUpdate.size()>0){
            update pipListToUpdate;
        }
        PageReference rejRedirect =new Pagereference('/apex/PipelnAppList');
        rejRedirect.setRedirect(true);
        return rejRedirect;
    }
    
   // Wrapper class 
    public class wrapPipeline{
        public AcqPipeline__c PipLin {get; set;}
        public Boolean selected {get; set;}
        // wrapper construction
        public wrapPipeline(AcqPipeline__c p){
            PipLin = p;
            selected = false;
        }
    }
    
   
}