mdapi/Custom/objects/AZB_Update__c.object
<CustomObject>
    <description>This object is the message queue for all AZ Bidder updates.
They will send records to this queue for each update and insert triggers will apply the business logic.  Note that these messages may indicate changes in Prospects or Pipeline records.</description>
    <fields>
        <fullName>Address_Validated_City__c</fullName>
        <label>Address Validated City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validated_County__c</fullName>
        <label>Address Validated County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validated_Last_Attempt__c</fullName>
        <label>Address Validated Last Attempt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Address_Validated_State__c</fullName>
        <label>Address Validated State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validated_Street__c</fullName>
        <label>Address Validated Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validated_Successfully__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Address Validated Successfully</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Validated_Zip__c</fullName>
        <label>Address Validated Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Validation_Message__c</fullName>
        <label>Address Validation Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipPlus4__c</fullName>
        <label>ZipPlus4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>AZB Update</label>
    <nameField>
        <displayFormat>AZBU-{0000}</displayFormat>
        <label>AZB Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AZB Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/classes/AZB_UpdateService.cls
/**
 *  Description :   AZB Update Service Class.
 *
 *  Created By  :   Abhinav Sharma
 *
 *  Created Date:   05/24/2013
 *
 *  Revision Logs:  V1.0 - Created
 *					
 *
 **/ 
public with sharing class AZB_UpdateService {
	
	//This method is to update the main record with the validated address recsponse
	public static void updateAddressValidationResults(List<IHSmartyStreetsService.ValidateAddressResponse> results) {
		
		//Create a list of residence records to be updated
		List<AZB_Update__c> aZBRecords = new List<AZB_Update__c>();
				
		//loop thorugh the response
		for(IHSmartyStreetsService.ValidateAddressResponse response : results) {
			
			//Create a clone of resedense
			AZB_Update__c aZB = new AZB_Update__c(Id = response.recordId);
				
			//Update validated data on residence
 			aZB.Address_Validated_Street__c = response.street;
			aZB.Address_Validated_City__c = response.city;
			aZB.Address_Validated_Zip__c = response.zip;
			aZB.Address_Validated_State__c = response.state;
			aZB.Address_Validated_Last_Attempt__c = DateTime.now();
			aZB.Address_Validated_Successfully__c = response.validateSuccess;
				
			//Other fields
			aZB.ZipPlus4__c = response.zipPlus4;
			aZB.Location__Latitude__s =  response.latitude;
			aZB.Location__Longitude__s =  response.longitude;
			aZB.Address_Validated_County__c = response.county;
			aZB.Address_Validation_Message__c = response.errorMessage;
				
			//Add response in the list to be updated
			aZBRecords.add(aZB);
		}
		
		//Check for the lis size and update tre records
		if(aZBRecords.size() > 0)
			update aZBRecords;
	}
}