mdapi/Custom/objects/AZB_Update__c.object
<CustomObject>
    <description>This object is the message queue for all AZ Bidder updates.
They will send records to this queue for each update and insert triggers will apply the business logic.  Note that these messages may indicate changes in Prospects or Pipeline records.</description>
    <fields>
        <fullName>AZB_ID__c</fullName>
        <description>This is AZBidder&apos;s File Id.  It is required, and their external ID.</description>
        <externalId>true</externalId>
        <label>AZB ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IH_Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the pipeline record created for the AZB record upsert.</description>
        <label>IH Pipeline</label>
        <referenceTo>Property_Opportunity__c</referenceTo>
        <relationshipLabel>AZB Updates</relationshipLabel>
        <relationshipName>AZB_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IH_Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the prospect created for this AZB_Update master record.</description>
        <label>IH Prospect</label>
        <referenceTo>Prospect__c</referenceTo>
        <relationshipLabel>AZB Updates</relationshipLabel>
        <relationshipName>AZB_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AZB Update</label>
    <nameField>
        <displayFormat>AZBU-{0000}</displayFormat>
        <label>AZB Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AZB Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property__c.object
<CustomObject>
    <description>This is the output of the Acquisition reporting process and is the primary &quot;purchase record&quot; of all of our properties.</description>
    <fields>
        <fullName>Acquisition_Status__c</fullName>
        <label>Acquisition Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquired</fullName>
                    <default>true</default>
                    <label>Acquired</label>
                </value>
                <value>
                    <fullName>Limbo</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>For Sale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline</label>
        <referenceTo>Property_Opportunity__c</referenceTo>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up field that links the portfolio record to the related prospect.</description>
        <label>Prospect</label>
        <referenceTo>Prospect__c</referenceTo>
        <relationshipLabel>Portfolio Record with Post-Acquisition Details</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Portfolio</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property_Opportunity__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment.  This object captures properties that have been placed into escrow and where the Approval process occurs that facilitates reporting and creation of Portfolio.</description>
    <fields>
        <fullName>AZB_ID__c</fullName>
        <formula>AZB_Update__r.AZB_ID__c</formula>
        <label>AZB ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AZB_Update__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AZB Update</label>
        <referenceTo>AZB_Update__c</referenceTo>
        <relationshipLabel>Pipeline</relationshipLabel>
        <relationshipName>Pipeline</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Atlanta_Auction__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a temp field only for the Atlanta team to use for Super Tuesday.</inlineHelpText>
        <label>Atlanta Auction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsConverted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect</label>
        <referenceTo>Prospect__c</referenceTo>
        <relationshipLabel>Pipeline Record with Acquisition Details</relationshipLabel>
        <relationshipName>Pipeline</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Pipeline</relationshipLabel>
        <relationshipName>Pipeline</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>*Pipeline Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Active - Bid Placed</fullName>
                </value>
                <value>
                    <fullName>Active - In Escrow</fullName>
                </value>
                <value>
                    <fullName>Dead - Bid Lost</fullName>
                </value>
                <value>
                    <fullName>Dead - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Dead  - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Bid Lost</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed  - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/Custom/objects/Prospect__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment and is the &quot;entry point&quot; for all records from brokers or AZ bidder.</description>
    <fields>
        <fullName>AZB_ID__c</fullName>
        <formula>AZB_Update__r.AZB_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AZB ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AZB_Update__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AZB Update</label>
        <referenceTo>AZB_Update__c</referenceTo>
        <relationshipLabel>Prospect</relationshipLabel>
        <relationshipName>Prospect</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsConverted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Pipeline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prospect_Status__c</fullName>
        <label>Prospect Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open - Under Review</fullName>
                </value>
                <value>
                    <fullName>Open - In Contract</fullName>
                </value>
                <value>
                    <fullName>Dead - Declined</fullName>
                </value>
                <value>
                    <fullName>Dead - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Dead - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Dead - No Activity</fullName>
                </value>
                <value>
                    <fullName>Converted to Pipeline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Prospect</relationshipLabel>
        <relationshipName>Prospect</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PROS-{0000}</displayFormat>
        <label>Prospect Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospect</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Residence__c.object
<CustomObject>
    <description>This is the &quot;parent&quot; account of all Portfolio records and represents a property address.</description>
    <fields>
        <fullName>Atlanta_Auction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Atlanta Auction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline</label>
        <referenceTo>AcqPipeline__c</referenceTo>
        <relationshipLabel>Residences</relationshipLabel>
        <relationshipName>Residences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect</label>
        <referenceTo>Acq_Prospect__c</referenceTo>
        <relationshipLabel>Residences</relationshipLabel>
        <relationshipName>Residences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Win_Date__c</fullName>
        <label>Win Date</label>
        <type>Date</type>
    </fields>
    <label>Residence</label>
    <nameField>
        <displayFormat>RES-{00000}</displayFormat>
        <label>Residence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/AZBUpdateRescindSaleExtension.cls
public with sharing class AZBUpdateRescindSaleExtension {
	
	ApexPages.StandardController ctrl;
	
	// Constructor
	public AZBUpdateRescindSaleExtension(ApexPages.StandardController stdController){
		if(stdController == null || stdController.getId() == null) {
			VFUtil.AddErrorMessage('No AZB update record passed to the page.');
			return;
		}
		ctrl = stdController;
	}
	
	// Function to Rescind Sale	
	public PageReference rescindSale() {
		
		Savepoint sp = Database.setSavepoint();	
		try {
			if(ctrl != null) {
				Boolean updateProspect = false;
				Boolean updatePipeline = false;
				Boolean updateResidence = false;
				
				// Get AZB Update record detail
				AZB_Update__c azbUpdate = [Select IH_Pipeline__c, IH_Prospect__c, AZB_ID__c from AZB_Update__c 
																							where Id = : ctrl.getId()];
																							
				// Check if record is already rescinded.
				if(String.isNotBlank(azbUpdate.AZB_ID__c) && azbUpdate.AZB_ID__c.contains('-R')) {
					VFUtil.AddErrorMessage('This sales has already been rescinded; it cannot be rescinded again.');
					return null;	
				}
																											
				// Update Prospect
				Prospect__c prospect;
				if(azbupdate.IH_Prospect__c != null) {
					prospect  = [Select Prospect_Status__c, Residence__c, IsConverted__c from Prospect__c 
																						where Id = :azbupdate.IH_Prospect__c];
					if(!prospect.IsConverted__c) {
						prospect.Prospect_Status__c = 'Dead - Cancelled';
						updateProspect = true;
					}
				}
				
				// Update Pipeline
				Property_Opportunity__c pipeline ;
				if(azbupdate.IH_Pipeline__c != null) {	 
					 
					pipeline = [Select IsConverted__c, Stage__c from Property_Opportunity__c where Id = :azbupdate.IH_Pipeline__c];
					
					if (pipeline.IsConverted__c) {
						List<Property__c> portfolio = [Select Acquisition_Status__c from Property__c 
																					where Pipeline__c = :pipeline.Id
																					and Acquisition_Status__c != 'Cancelled'];
						if(portfolio != null && portfolio.size() > 0) {
							VFUtil.AddErrorMessage('You may not rescind a sale that is already converted to an active Portfolio record.'
														+ ' Contact Asset Management to cancel the Portfolio record.');
							return null;
						}
						else {
							pipeline.Stage__c = 'Dead - Cancelled';
							updatePipeline = true;
						}
					}
					else {
						pipeline.Stage__c = 'Dead - Cancelled';
						updatePipeline = true;
					}
				}
				
				// Update AZB ID 
				String azbId = azbupdate.AZB_ID__c + '-R%';
				System.debug('abxID: ' + azbId);
				List<AZB_Update__c> prevAZBRecs = [select Id from AZB_Update__c where AZB_ID__c like :azbId];
				
				azbUpdate.AZB_ID__c += (prevAZBRecs == null || prevAZBRecs.size() == 0) ? '-R' : '-R' + prevAZBRecs.size();
				
				// Update Residence
				Residence__c residence;
				if(prospect != null && prospect.Residence__c != null) {
					residence = new Residence__c(Id = prospect.Residence__c);
					residence.Atlanta_Auction__c = false;
					residence.Win_Date__c = null;
					updateResidence = true;
				}
				
				// Update the records
				update azbUpdate;
				
				if(updateProspect)
					update prospect;
					
				if(updatePipeline)
					update pipeline;
				
				if(updateResidence)
					update residence;
				
				PageReference azpPage = ctrl.view();
				azpPage.setRedirect(true);
				return azpPage;
			}
		}
		catch(Exception e) {
			Database.rollback(sp);	
			VFUtil.AddErrorMessage('You may not rescind sales outside your own region.');
		}
		return null;
	}	
}