mdapi/Custom/objects/Bidding_Statistics__c.object
<CustomObject>
    <description>This is the object that is created by the region to submit their daily bidding statistics.  At the conclusion of the Acquisition Reporting process, data is also written back to the daily BSN record. (JMH 1.2.13)</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bidding Statistics</label>
    <nameField>
        <displayFormat>BSN-{0000000}</displayFormat>
        <label>Bidding Statistics Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidding Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Custom--app/main/default/classes/Override_AcqReportingNewController.cls
/**
 *  Description :   This class is to call methods from Javascript.
 *
 *  Created By  :   Bhavi Sharma
 *
 *  Created Date:   12/22/2012
 *
 *  Revision Logs:  V1.0 - Created
 *
 **/
public without sharing class Override_AcqReportingNewController {
	
	//Standard controller
	public Override_AcqReportingNewController(ApexPages.StandardController controller) {
		
	}
	
	//Get user region
	public PageReference validateRedirect() {
		
		//Get user region
		User user = [Select Id, Region__c from User where Id =: UserInfo.getUserId()];
		
		//redirect to page
		PageReference pageRef = new PageReference('/' + Bidding_Statistics__c.sObjectType.getDescribe().getKeyPrefix() + '/e');
		
		//Add parameters
		pageRef.getParameters().put('retURL', '/' + Bidding_Statistics__c.sObjectType.getDescribe().getKeyPrefix());
		pageRef.getParameters().put(Constants.VIEW_CONFIGURATION.Acquisition_Reporting_Region__c, user.Region__c);
		pageRef.getParameters().put('nooverride', '1');
		
		//return
		return pageRef;
	}
}