mdapi/Custom/objects/Change_Orders__c.object
<CustomObject>
    <description>This is part of the Rehab deployment.  It is used by the Rehab team to track change orders.  (This may go away or be amended based on the phase two integration plans for the HD application.)</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Change_Order_Type__c</fullName>
        <label>Change Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Increase</fullName>
                </value>
                <value>
                    <fullName>Reduction</fullName>
                </value>
                <value>
                    <fullName>Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GL_Code_Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Change_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Type_Adjusted__c</fullName>
        <formula>IF( ISPICKVAL( Rehab__r.Type__c, &apos;Post-Acquisition&apos; ), 
    IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
        , GL_Code_Original__r.Name, 
        GL_Code_Original__r.GL_Code_Acquisition__r.Name 
      ), 
    IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
        GL_Code_Original__r.Name, 
        GL_Code_Original__r.GL_Code_Turn__r.Name 
      ) 
  )</formula>
        <label>GL Code Type Adjusted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Code__c</fullName>
        <label>GL Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1260100 - Rehab Other</fullName>
                </value>
                <value>
                    <fullName>1260125 - Rehab Demo/Waste</fullName>
                </value>
                <value>
                    <fullName>1260140 - Rehab Pests/Termites</fullName>
                </value>
                <value>
                    <fullName>1260150 - Rehab Cleaning</fullName>
                </value>
                <value>
                    <fullName>1260175 - Rehab Initial Re-Key</fullName>
                </value>
                <value>
                    <fullName>1260200 - Rehab General Contractor</fullName>
                </value>
                <value>
                    <fullName>1260210 - Rehab GC Change Order</fullName>
                </value>
                <value>
                    <fullName>1260300 - Rehab Roofs</fullName>
                </value>
                <value>
                    <fullName>1260325 - Rehab Garage and Garage Doors</fullName>
                </value>
                <value>
                    <fullName>1260350 - Rehab Exterior Surfaces</fullName>
                </value>
                <value>
                    <fullName>1260375 - Rehab Sidewalks/Driveways</fullName>
                </value>
                <value>
                    <fullName>1260400 - Rehab Cabinets</fullName>
                </value>
                <value>
                    <fullName>1260425 - Rehab Interior Painting</fullName>
                </value>
                <value>
                    <fullName>1260450 - Rehab Flooring</fullName>
                </value>
                <value>
                    <fullName>1260475 - Rehab Door/Window Costs</fullName>
                </value>
                <value>
                    <fullName>1260480 - Rehab Blinds</fullName>
                </value>
                <value>
                    <fullName>1260500 - Rehab Countertops</fullName>
                </value>
                <value>
                    <fullName>1260600 - Rehab Landscape</fullName>
                </value>
                <value>
                    <fullName>1260700 - Rehab Pool Service Fees</fullName>
                </value>
                <value>
                    <fullName>1260710 - Rehab Pool Maintenance Costs</fullName>
                </value>
                <value>
                    <fullName>1260800 - Rehab Appliances</fullName>
                </value>
                <value>
                    <fullName>1260825 - Rehab Specialty Electric</fullName>
                </value>
                <value>
                    <fullName>1260850 - Rehab Specialty Plumbing</fullName>
                </value>
                <value>
                    <fullName>1260900 - Rehab HVAC</fullName>
                </value>
                <value>
                    <fullName>1260910 - Rehab Utilities</fullName>
                </value>
                <value>
                    <fullName>1260915 - Rehab Utilities Prior Ownership</fullName>
                </value>
                <value>
                    <fullName>1261000 - Rehab Capitalized Insurance</fullName>
                </value>
                <value>
                    <fullName>1261100 - Rehab Capitalized Tax</fullName>
                </value>
                <value>
                    <fullName>1261200 - Rehab Capitalized Interest</fullName>
                </value>
                <value>
                    <fullName>1261300 - Rehab Capitalized HOA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rehab_Projected_Spend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab Projected Spend</label>
        <referenceTo>Rehab_Projected_Spend__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Change_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Change_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected_Approved_Bid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check the box if this was the selected Bid</inlineHelpText>
        <label>Selected &amp; Approved Bid</label>
        <type>Checkbox</type>
    </fields>
    <label>Change Orders</label>
    <nameField>
        <displayFormat>Change#{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/GL_Code__c.object
<CustomObject>
    <fields>
        <fullName>GL_Code_Acquisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code Acquisition</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>GL Codes (GL Code Acquisition)</relationshipLabel>
        <relationshipName>GL_Codes_Acquisition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Turn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code Turn</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>GL Codes (GL Code Turn)</relationshipLabel>
        <relationshipName>GL_Codes_Turn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/HD_Budget_Walk__c.object
<CustomObject>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab ID</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipName>HD_Budget_Walks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submit_Date__c</fullName>
        <label>Submit Date</label>
        <type>DateTime</type>
    </fields>
    <label>HD Budget Walk</label>
    <nameField>
        <displayFormat>BW-{000000}</displayFormat>
        <label>HD Budget Walk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HD Budget Walks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab__c.object
<CustomObject>
    <description>This is the central record for the Rehab deployment.  Tracks all key details relating to the Rehab process.</description>
    <fields>
        <fullName>HD_Budget_Walk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HD Budget Walk</label>
        <referenceTo>HD_Budget_Walk__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Spend_Changes_To_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total amount of change orders</inlineHelpText>
        <label>Change Order Running Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rehab_Status__c</fullName>
        <formula>CASE(Stage__c,
&quot;Notification Received&quot;,&quot;Active - Pending Move Out&quot;,
&quot;Ready to Schedule MOI/Utility Transfer&quot;,&quot;Active - Pending Move Out&quot;,
&quot;Move Out Scheduled&quot;,&quot;Active - Pending Move Out&quot;,
&quot;Move Out Assigned&quot;,&quot;Active - Pending Move Out&quot;,
&quot;GC Awarded&quot;,&quot;Active - In Process&quot;,
&quot;Five Day Complete&quot;,&quot;Active - In Process&quot;,
&quot;Final Inspection Pass / QC Ready&quot;,&quot;Active - In Process&quot;,
&quot;Final Inspection Pass&quot;,&quot;Active - In Process&quot;,
&quot;QC Assigned&quot;,&quot;Active - In Process&quot;,
&quot;QC Open&quot;,&quot;Active - In Process&quot;,
&quot;QC Closed&quot;,&quot;Active - In Process&quot;,
&quot;2 Day Walk Complete&quot;,&quot;Active - In Process&quot;,
&quot;Closed - Completed&quot;,&quot;Completed&quot;,
&quot;Closed - Cancelled&quot;,&quot;Completed&quot;,
&quot;Closed - No Rehab Needed&quot;,&quot;Completed&quot;,
&quot;Complete&quot;,&quot;Completed&quot;,
&quot;HOLD - BK&quot;,&quot;HOLD - BK/Deed&quot;,
&quot;HOLD - Deed&quot;,&quot;HOLD - BK/Deed&quot;,
&quot;HOLD - Notification Revoked/Cancel Utility Transfer&quot;,&quot;HOLD - Notification Revoked&quot;,
&quot;HOLD - Occupied/TIP&quot;,&quot;HOLD - TIP&quot;,
&quot;HOLD - Permits&quot;,&quot;Active - Pre-Construction&quot;,
&quot;HOLD - Sell&quot;,&quot;HOLD - Sell&quot;,
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rehab Status</label>
        <type>Text</type>
    </fields>
    <label>Rehab</label>
    <nameField>
        <displayFormat>RHB-{0000}</displayFormat>
        <label>Rehab Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab_Projected_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Changes_To_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Changes To Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GL_Code_Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Type_Adjusted__c</fullName>
        <formula>IF( NOT(ISNULL(Rehab__c)) , 
      IF( ISPICKVAL( Rehab__r.Type__c, &apos;Post-Acquisition&apos; ), 
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
                      , GL_Code_Original__r.Name, 
                      GL_Code_Original__r.GL_Code_Acquisition__r.Name 
          ),
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
                      GL_Code_Original__r.Name,  
                      GL_Code_Original__r.GL_Code_Turn__r.Name ) 
        ),
      IF( OR( ISPICKVAL( HD_Budget_Walk__r.Type__c, &apos;Pre-Acquisitions&apos; ),
              ISPICKVAL( HD_Budget_Walk__r.Type__c, &apos;Post-Acquisitions&apos; ) ),   
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
                      , GL_Code_Original__r.Name, 
                      GL_Code_Original__r.GL_Code_Acquisition__r.Name 
          ),
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
                      GL_Code_Original__r.Name,  
                      GL_Code_Original__r.GL_Code_Turn__r.Name )
        )
    )</formula>
        <label>GL Code Type Adjusted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Code__c</fullName>
        <label>Obsolete GL Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HD_Budget_Walk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HD Budget Walk</label>
        <referenceTo>HD_Budget_Walk__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Running_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Running Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rehab Projected Spend</label>
    <nameField>
        <displayFormat>RPS-{00000000}</displayFormat>
        <label>RPS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehab Projected Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/Change_OrdersTriggerHelper.cls
/**
 *   Description  :  Helper Class for Trigger_Change_Orders on Change_Orders__c Object
 *
 *   Created By Shrinath
 *
 *   Created Date:  08/23/2013
 *
 *   Revision Logs:  V1.0 - Created
 **/
public without sharing class Change_OrdersTriggerHelper {

    // Boolean to remove validation for GL Code Required, It will be false from test method of GLCodeSyncTest class
    public static Boolean validateGLCodeRequired = true;

    /*
        Method to populate rehab projected spend
    */
    public static void populateRehabProjectedSpend( List<Change_Orders__c> newChangeOrders,
                                                    Map<Id, Change_Orders__c> oldMapChangeOrders ) {

        Set<String> setGLCodesTypeAdjusted = new Set<String>();
        Set<Id> setRehabIds = new Set<Id>();

        for( Change_Orders__c coObj : newChangeOrders ) {

            if( coObj.GL_Code_Original__c == null && validateGLCodeRequired ) {
                coObj.GL_Code_Original__c.addError( 'Please enter a value in GL Code' );
            }
            else {
                if( trigger.isInsert || coObj.Rehab_Projected_Spend__c == null ) {
                    setRehabIds.add(coObj.Rehab__c);
                    setGLCodesTypeAdjusted.add( coObj.GL_Code_Type_Adjusted__c );
                }
            }
        }

        Map<Id, Rehab__c> mapRehab = new Map<Id, Rehab__c>( [ Select RecordType.Name,
                                                                     Rehab_Status__c,
                                                                     Hd_Budget_Walk__r.Submit_Date__c               
                                                               From Rehab__c
                                                               Where Id =: setRehabIds
                                                             ]);

        // query rehab projected spend
        List<Rehab_Projected_Spend__c> listRehabProjectedSpends = [Select Id,
                                                                          Rehab__c,
                                                                          GL_Code_Original__c,
                                                                          GL_Code_Type_Adjusted__c
                                                                   From Rehab_Projected_Spend__c
                                                                   Where GL_Code_Type_Adjusted__c in: setGLCodesTypeAdjusted
                                                                   And Rehab__c in: setRehabIds];

        Map<String, Rehab_Projected_Spend__c> mapGLCodeToRehabProjectedSpend = new Map<String, Rehab_Projected_Spend__c>();

        Map<String, Rehab_Projected_Spend__c> mapGLCodeToRehabProjectedSpendToInsert = new Map<String, Rehab_Projected_Spend__c>();

        for( Rehab_Projected_Spend__c rpsObj : listRehabProjectedSpends ) {
            if( rpsObj.GL_Code_Original__c != null && rpsObj.GL_Code_Type_Adjusted__c != null ) {
                String mapKey = rpsObj.Rehab__c + rpsObj.GL_Code_Type_Adjusted__c.trim().toLowerCase();
                mapGLCodeToRehabProjectedSpend.put( mapKey, rpsObj );
            }

        }

        Map<String, GL_Code__c> mapGLCodeNameToGLCode = new Map<String, GL_Code__c>();
        // Query GL Codes
        Map<Id, GL_Code__c> mapGLCode = new Map<Id, GL_Code__c>( [ Select Name,
                                                                          GL_Code_Acquisition__c,
                                                                          GL_Code_Turn__c,
                                                                          GL_Code_Acquisition__r.Name,
                                                                          GL_Code_Turn__r.Name
                                                                   From GL_Code__c
                                                                   Where Name !=: Null
                                                                 ]);
        for( GL_Code__c glCodeObj : mapGLCode.values() ) {
            mapGLCodeNameToGLCode.put( glCodeObj.Name.trim().toLowerCase(), glCodeObj );
        }
        
        for( Change_Orders__c coObj : newChangeOrders ) {
              if( coObj.GL_Code_Original__c != null
                  && coObj.Rehab__c != null
                  && coObj.Rehab_Projected_Spend__c == null ) {

                    String mapKey = coObj.Rehab__c + coObj.GL_Code_Type_Adjusted__c.trim().toLowerCase();
                    if( !mapGLCodeToRehabProjectedSpend.containsKey( mapKey ) ) {
                          Rehab__c rehab = mapRehab.get( coObj.Rehab__c );
                          // Changes done for SIR D-00014800 
                          Boolean isRehabInProgress = false;
                          if( !RehabProjectedSpendController.stopRPSInsertUpdateRTMSprintChangesPhase2() ) {
                              isRehabInProgress = RehabProjectedSpendController.rehabProjectedSpendRTMSprintChanges() ? false : true;
                              if( !isRehabInProgress ) {
                                    if( rehab.Rehab_Status__c != null 
                                        && rehab.Rehab_Status__c.containsIgnoreCase('In Process')
                                        && rehab.Hd_Budget_Walk__r.Submit_Date__c != null 
                                        && rehab.Hd_Budget_Walk__r.Submit_Date__c <= RehabProjectedSpendController.rtmSprintDate ) {
                                     
                                           isRehabInProgress = true;
                                     }
                              }
                          }        
                                                                    
                          if( isRehabInProgress ) { 
                            
                              GL_Code__c glCodeObj = mapGLCode.get( coObj.GL_Code_Original__c );
    
                              String glCodeTypeAdjusted = GL_Code_Service.getTypeAdjustedGLCode( glCodeObj, rehab );
                              GL_Code__c glCodeTypeAdjustedObj = mapGLCodeNameToGLCode.get( glCodeTypeAdjusted.trim().toLowerCase() );
                              mapGLCodeToRehabProjectedSpendToInsert.put( mapKey, new Rehab_Projected_Spend__c( Running_Total__c = 0,
                                                                                                                Rehab__c = coObj.Rehab__c,
                                                                                                                GL_Code_Original__c = glCodeTypeAdjustedObj.Id ) );
                         }
                    }
              }
        }
        
        if( mapGLCodeToRehabProjectedSpendToInsert.size() > 0 ) {
            insert mapGLCodeToRehabProjectedSpendToInsert.values();
        }
        mapGLCodeToRehabProjectedSpend.putAll( mapGLCodeToRehabProjectedSpendToInsert );
        for( Change_Orders__c coObj : newChangeOrders ) {

            if( coObj.GL_Code_Original__c != null
                    && coObj.Rehab__c != null
                    && coObj.Rehab_Projected_Spend__c == null ) {

                String mapKey = coObj.Rehab__c + coObj.GL_Code_Type_Adjusted__c.trim().toLowerCase();
                if(mapGLCodeToRehabProjectedSpend.containsKey( mapKey ) ) {
                    coObj.Rehab_Projected_Spend__c = mapGLCodeToRehabProjectedSpend.get( mapKey ).Id;
                }
            }
        }

    }

    /*
    	// Changes done for SIR D-00014800
        Method to update rehab projected spend
    */
    public static void updateRehab( List<Change_Orders__c> newChangeOrders,
                  	                Map<Id, Change_Orders__c> oldMapChangeOrders) {
    
    
		Set<Id> setRehabIds = new Set<Id>();
		
		List<Change_Orders__c> allowedChangeOrders = new List<Change_Orders__c>();
		
		for( Change_Orders__c coObj : newChangeOrders ) {

               if( coObj.Rehab__c != null
                                      &&
                                      (
                                            Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Amount__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Selected_Approved_Bid__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Change_Order_Type__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Rehab_Projected_Spend__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Rehab__c')
                                       ) ) {
					
                    setRehabIds.add( coObj.Rehab__c );
					allowedChangeOrders.add( coObj );
               }
        }
		
		if( setRehabIds.size() > 0 ) {
			
		
			Map<Id, Rehab__c> mapRehabs = new Map<Id, Rehab__c>(
	                                                               [Select Id,
	                                                                       Projected_Spend_Changes_To_Budget__c,
	                                                                       Selected_Bid_Total__c
	                                                                From Rehab__c
	                                                                Where Id in: setRehabIds
	                                                               ]
	                                                              );
	
	        Map<Id, Rehab__c> mapRehabsToUpdate = new map<Id, Rehab__c>();
        
	        for( Change_Orders__c coObj : allowedChangeOrders ) {
	
	                    // when mapRehabs has rehab 
	                    if( mapRehabs.containsKey( coObj.Rehab__c ) ) {
	
	                        Rehab__c rehab = mapRehabs.get( coObj.Rehab__c );
	                        
	                        // when insert trigger context
	                        if( trigger.isInsert ) {
	                            // when Change_Order_Type not equals to "Bid"
	                            if( coObj.Change_Order_Type__c != 'Bid' ) {
	                                rehab.Projected_Spend_Changes_To_Budget__c = returnZeroIfInputNull( rehab.Projected_Spend_Changes_To_Budget__c )
	                                                              + returnZeroIfInputNull( coObj.Amount__c );
	                            }
	                            // when Change_Order_Type not equals "Bid" and Selected_Approved_Bid is True
	                            if( coObj.Change_Order_Type__c == 'Bid' && coObj.Selected_Approved_Bid__c ) {
	                                rehab.Selected_Bid_Total__c = returnZeroIfInputNull( rehab.Selected_Bid_Total__c )
	                                                              + returnZeroIfInputNull( coObj.Amount__c );
	                            }
	                        }
	                        if( trigger.isUpdate ) {
	                            
                                // when Change_Order_Type not equals to "Bid"
                                if( coObj.Change_Order_Type__c != 'Bid' ) {
                                    // when condition was matched earlier
                                    if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c != 'Bid' ) {
                                        rehab.Projected_Spend_Changes_To_Budget__c = returnZeroIfInputNull( rehab.Projected_Spend_Changes_To_Budget__c )
				                                                                      + returnZeroIfInputNull( coObj.Amount__c )
				                                                                      - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );
                                    }
                                    else {
                                            rehab.Projected_Spend_Changes_To_Budget__c = returnZeroIfInputNull( rehab.Projected_Spend_Changes_To_Budget__c )
                                                                          + returnZeroIfInputNull( coObj.Amount__c );
                                    }
                                }
                                // when condition was matched earlier
                                else if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c != 'Bid' ) {

                                    rehab.Projected_Spend_Changes_To_Budget__c = returnZeroIfInputNull( rehab.Projected_Spend_Changes_To_Budget__c )
                                                                  - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );

                                }

                                // when Change_Order_Type equals "Bid" and Selected_Approved_Bid is True
                                if( coObj.Change_Order_Type__c == 'Bid' && coObj.Selected_Approved_Bid__c ) {
                                    // when condition was matched earlier
                                    if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c == 'Bid' && oldMapChangeOrders.get( coObj.Id ).Selected_Approved_Bid__c ) {
                                        rehab.Selected_Bid_Total__c = returnZeroIfInputNull( rehab.Selected_Bid_Total__c )
                                                                       + returnZeroIfInputNull( coObj.Amount__c )
                                                                       - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );
                                    }
                                    else {
                                        rehab.Selected_Bid_Total__c = returnZeroIfInputNull( rehab.Selected_Bid_Total__c )
                                                                       + returnZeroIfInputNull( coObj.Amount__c );

                                    }
                                }
                                // when condition was matched earlier
                                else if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c == 'Bid' && oldMapChangeOrders.get( coObj.Id ).Selected_Approved_Bid__c ) {

                                            rehab.Selected_Bid_Total__c = returnZeroIfInputNull( rehab.Selected_Bid_Total__c )
                                                                           - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );

                                }
                            
	                        }
	                        
	                    	mapRehabsToUpdate.put( rehab.Id, rehab );
	                    }
	               }
	               
	               if( mapRehabsToUpdate.size() > 0 ) {
	               		update mapRehabsToUpdate.values();
	               }	        
		}
        
    }
    
    /*
        Method to update rehab projected spend
    */
    /*
    // Commented the code for : // Changes done for SIR D-00014800
    public static void updateRehabProjectedSpend( List<Change_Orders__c> newChangeOrders,
                                                  Map<Id, Change_Orders__c> oldMapChangeOrders) {

    	
        Set<Id> setRehabProjectedSpendIds = new Set<Id>();
        for( Change_Orders__c coObj : newChangeOrders ) {

               if( coObj.Rehab_Projected_Spend__c != null
                                      &&
                                      (
                                            Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Amount__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Selected_Approved_Bid__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Change_Order_Type__c')
                                         || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Rehab_Projected_Spend__c')
                                       ) ) {

                    if(  trigger.isUpdate && Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Rehab_Projected_Spend__c') ) {
                        Id rpsIdOld = oldMapChangeOrders.get( coObj.Id ).Rehab_Projected_Spend__c;
                        if( rpsIdOld != null ) {
                            setRehabProjectedSpendIds.add( rpsIdOld );
                        }
                    }
                    setRehabProjectedSpendIds.add(coObj.Rehab_Projected_Spend__c);

               }
        }

        Map<Id, Rehab_Projected_Spend__c> mapRehabProjectedSpends = new Map<Id, Rehab_Projected_Spend__c>(
                                                                                                           [Select Id,
                                                                                                                   Changes_To_Budget__c,
                                                                                                                   Base_Budget_Amount__c,
                                                                                                                   Base_Budget_Reported_Timestamp__c,
                                                                                                                   Running_Total__c,
                                                                                                                   Rehab__c,
                                                                                                                   GL_Code_Original__c,
                                                                                                                   Revised_Budget__c,
                                                                                                                   Selected_Bid_Total__c,
                                                                                                                   Rehab__r.Projected_Spend_Running_Total__c,
                                                                                                                   Rehab__r.Projected_Spend_Changes_To_Budget__c,
                                                                                                                   Rehab__r.Selected_Bid_Total__c
                                                                                                            From Rehab_Projected_Spend__c
                                                                                                            Where Id in: setRehabProjectedSpendIds
                                                                                                           ]
                                                                                                          );

        Map<Id, Rehab__c> mapRehabsToUpdate = new map<Id, Rehab__c>();

        for( Change_Orders__c coObj : newChangeOrders ) {


                // when change order is associated with rehab projeccted spend
                if( coObj.Rehab_Projected_Spend__c != null
                          &&
                            (   Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Amount__c')
                                || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Selected_Approved_Bid__c')
                                || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Change_Order_Type__c')
                                || Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Rehab_Projected_Spend__c')
                             )
                                ) {

                    // when mapRehabProjectedSpends has rehab projeccted spend
                    if( mapRehabProjectedSpends.containsKey( coObj.Rehab_Projected_Spend__c ) ) {

                        Rehab_Projected_Spend__c rpsObj = mapRehabProjectedSpends.get( coObj.Rehab_Projected_Spend__c );
                        Rehab__c rehab;

                        if( !mapRehabsToUpdate.containsKey( rpsObj.Rehab__c ) ) {
                            // create rehab instancce
                            rehab = new Rehab__c( Id = rpsObj.Rehab__c,
                                                  Projected_Spend_Running_Total__c = ( rpsObj.Rehab__r.Projected_Spend_Running_Total__c == null ? 0 : rpsObj.Rehab__r.Projected_Spend_Running_Total__c ),
                                                  Projected_Spend_Changes_To_Budget__c = ( rpsObj.Rehab__r.Projected_Spend_Changes_To_Budget__c == null ? 0 : rpsObj.Rehab__r.Projected_Spend_Changes_To_Budget__c ),
                                                  Selected_Bid_Total__c = ( rpsObj.Rehab__r.Selected_Bid_Total__c == null ? 0 : rpsObj.Rehab__r.Selected_Bid_Total__c )
                                                );
                        }
                        else {
                            rehab = mapRehabsToUpdate.get( rpsObj.Rehab__c );
                        }

                        // when insert trigger context
                        if( trigger.isInsert ) {
                            // when Change_Order_Type not equals to "Bid"
                            if( coObj.Change_Order_Type__c != 'Bid' ) {
                                rpsObj.Changes_To_Budget__c = returnZeroIfInputNull( rpsObj.Changes_To_Budget__c )
                                                              + returnZeroIfInputNull( coObj.Amount__c );
                            }
                            // when Change_Order_Type not equals "Bid" and Selected_Approved_Bid is True
                            if( coObj.Change_Order_Type__c == 'Bid' && coObj.Selected_Approved_Bid__c ) {
                                rpsObj.Selected_Bid_Total__c = returnZeroIfInputNull( rpsObj.Selected_Bid_Total__c )
                                                              + returnZeroIfInputNull( coObj.Amount__c );
                            }
                        }
                        if( trigger.isUpdate ) {

                            //if reference Rehab_Projected_Spend__c is changed
                            if( Utility.hasFieldChanged( coObj, oldMapChangeOrders, 'Rehab_Projected_Spend__c') ) {

                                Id rpsIdOld = oldMapChangeOrders.get( coObj.Id ).Rehab_Projected_Spend__c;

                                if( rpsIdOld != null && mapRehabProjectedSpends.containsKey( rpsIdOld ) ) {

                                    Rehab_Projected_Spend__c rpsObjOldConnected = mapRehabProjectedSpends.get( rpsIdOld );

                                    // when Change_Order_Type not equals to "Bid"
                                    if( coObj.Change_Order_Type__c != 'Bid' ) {
                                        rpsObjOldConnected.Changes_To_Budget__c = returnZeroIfInputNull( rpsObjOldConnected.Changes_To_Budget__c )
                                                                      -  ( returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c ) );
                                    }
                                    // when Change_Order_Type not equals "Bid" and Selected_Approved_Bid is True
                                    if( coObj.Change_Order_Type__c == 'Bid' && coObj.Selected_Approved_Bid__c ) {
                                        rpsObjOldConnected.Selected_Bid_Total__c = returnZeroIfInputNull( rpsObjOldConnected.Selected_Bid_Total__c )
                                                                                   -  ( returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c ) );
                                    }
                                }

                                // when Change_Order_Type not equals to "Bid"
                                if( coObj.Change_Order_Type__c != 'Bid' ) {
                                    rpsObj.Changes_To_Budget__c = returnZeroIfInputNull( rpsObj.Changes_To_Budget__c )
                                                                  + returnZeroIfInputNull( coObj.Amount__c );
                                }
                                // when Change_Order_Type not equals "Bid" and Selected_Approved_Bid is True
                                if( coObj.Change_Order_Type__c == 'Bid' && coObj.Selected_Approved_Bid__c ) {
                                    rpsObj.Selected_Bid_Total__c = returnZeroIfInputNull( rpsObj.Selected_Bid_Total__c )
                                                                  + returnZeroIfInputNull( coObj.Amount__c );
                                }

                            }
                            else {

                                    // when Change_Order_Type not equals to "Bid"
                                    if( coObj.Change_Order_Type__c != 'Bid' ) {
                                        // when condition was matched earlier
                                        if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c != 'Bid' ) {
                                            rpsObj.Changes_To_Budget__c = returnZeroIfInputNull( rpsObj.Changes_To_Budget__c )
                                                                          + returnZeroIfInputNull( coObj.Amount__c )
                                                                          - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );
                                        }
                                        else {
                                                rpsObj.Changes_To_Budget__c = returnZeroIfInputNull( rpsObj.Changes_To_Budget__c )
                                                                              + returnZeroIfInputNull( coObj.Amount__c );
                                        }
                                    }
                                    // when condition was matched earlier
                                    else if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c != 'Bid' ) {

                                        rpsObj.Changes_To_Budget__c = returnZeroIfInputNull( rpsObj.Changes_To_Budget__c )
                                                                      - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );

                                    }

                                    // when Change_Order_Type equals "Bid" and Selected_Approved_Bid is True
                                    if( coObj.Change_Order_Type__c == 'Bid' && coObj.Selected_Approved_Bid__c ) {
                                        // when condition was matched earlier
                                        if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c == 'Bid' && oldMapChangeOrders.get( coObj.Id ).Selected_Approved_Bid__c ) {
                                            rpsObj.Selected_Bid_Total__c = returnZeroIfInputNull( rpsObj.Selected_Bid_Total__c )
                                                                           + returnZeroIfInputNull( coObj.Amount__c )
                                                                           - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );
                                        }
                                        else {
                                            rpsObj.Selected_Bid_Total__c = returnZeroIfInputNull( rpsObj.Selected_Bid_Total__c )
                                                                           + returnZeroIfInputNull( coObj.Amount__c );

                                        }
                                    }
                                    // when condition was matched earlier
                                    else if( oldMapChangeOrders.get( coObj.Id ).Change_Order_Type__c == 'Bid' && oldMapChangeOrders.get( coObj.Id ).Selected_Approved_Bid__c ) {

                                            rpsObj.Selected_Bid_Total__c = returnZeroIfInputNull( rpsObj.Selected_Bid_Total__c )
                                                                           - returnZeroIfInputNull( oldMapChangeOrders.get( coObj.Id ).Amount__c );

                                    }
                            }
                        }
                    }
               }
        }

        // update projected rehab spends
        if( mapRehabProjectedSpends.size() > 0 ) {
            update mapRehabProjectedSpends.values();
        }
		
    }
	*/
	
    private static Decimal returnZeroIfInputNull( Decimal inputVal ) {
        return ( inputVal == null ? 0 : inputVal );
    }
    
}