mdapi/Custom/objects/Concierge__c.object
<CustomObject>
    <description>This object will assist with the management of support related concepts across the Enterprise. It should be thought of in the traditional sense of a &quot;Case&quot;.</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Concierge</label>
    <nameField>
        <displayFormat>Ticket - {00000000}</displayFormat>
        <label>Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concierge</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Custom--app/main/default/classes/OverrideConciergeNewController.cls
/**
 *    Description       :    Apex Class used to open the Concierge Detail page based on User's Region
 *
 *    Created By        :    Poonam Bhargava
 *
 *    Created Date      :    02/15/2017    
 *
 *    Revision Logs     :    V1.0 - Created
 **/
public with sharing class OverrideConciergeNewController{
            
    //Initialize Constructor
    public OverrideConciergeNewController(ApexPages.StandardController controller) {
    }

    //Method to redirect the user on next screen based on User's Region
    public PageReference redirect(){
    
        //Get the record Type from Url
        String recordTypeId = Apexpages.currentPage().getParameters().get('RecordType');
        
        //Query on Record Type
        List<RecordType> recordTypes = [Select Id, Name, DeveloperName from RecordType where Id =: recordTypeId 
                                            AND DeveloperName !=: Label.Concierge_Record_Type_Treasury_Request 
                                            AND DeveloperName !=: Label.Concierge_Record_Type_Datamatics_Request];
    
        
        //Retrieve Users records
        //List<User> users = [Select Id, Region__c, Dallas_Office__c from User where Id =: UserInfo.getUserId() AND Region__c =: Constants.REGION_NATIONAL AND Dallas_Office__c = true]; 
        
        //Check for list size
        //if(users.size() > 0 && recordTypes.size() > 0){
        if(recordTypes.size() > 0){
            
            //Initialize the page reference variable and set target location
            return new PageReference('http://invitationhomes.service-now.com/');
        }
        else{
            
            //Initialize map of string and populate with url paramerter values
            Map<String, String> mapParams = ApexPages.currentPage().getParameters();
            
            //Get the key Prefix of Concierge object
            String  keyPrefix = Schema.getGlobalDescribe().get('Concierge__c').getDescribe().getKeyPrefix();
            
            //URL variable
            String url = '';
            
            //Loop over mapParams keyset
            for(String uRLParam : mapParams.keyset()){
                
                //Check for condition and populate url varible 
                if(uRLParam != 'save_new')
                    url += uRLParam + '=' + mapParams.get(uRLParam) + '&';  
            }  
            
            //Set nooverride value in url
            url += 'nooverride=1';
            
            //Set url in PageReference and return ref
            return new PageReference('/' + keyPrefix + '/e?'+url);                
        }      
		
        return null;
		
    }
}