mdapi/Custom/objects/Configuration_Manager__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SkipTriggersForUser; Residence, Prospect, Pipeline, and Portfolio settings.</description>
    <fields>
        <fullName>Parameter_Key__c</fullName>
        <label>Parameter Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameter_Value__c</fullName>
        <label>Parameter Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration Manager</label>
</CustomObject>

mdapi/Custom/objects/Property_Opportunity__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment.  This object captures properties that have been placed into escrow and where the Approval process occurs that facilitates reporting and creation of Portfolio.</description>
    <fields>
        <fullName>Bid_Type__c</fullName>
        <label>*Bid Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trustee</fullName>
                    <color>#F3D904</color>
                    <label>Trustee</label>
                </value>
                <value>
                    <fullName>REO</fullName>
                    <color>#78C953</color>
                    <label>REO</label>
                </value>
                <value>
                    <fullName>Bulk Sale</fullName>
                    <color>#993399</color>
                    <label>Bulk Sale</label>
                </value>
                <value>
                    <fullName>Short Sale</fullName>
                    <color>#E27001</color>
                    <label>Short Sale</label>
                </value>
                <value>
                    <fullName>Off Market</fullName>
                </value>
                <value>
                    <fullName>Retail Auction</fullName>
                </value>
                <value>
                    <fullName>Standard Sale - Investor</fullName>
                </value>
                <value>
                    <fullName>Standard Sale - Homeowner</fullName>
                </value>
                <value>
                    <fullName>Standard Sale</fullName>
                    <color>#CC0000</color>
                    <label>Standard Sale</label>
                </value>
                <value>
                    <fullName>New Build</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline</pluralLabel>
    <recordTypes>
        <fullName>Trustee</fullName>
        <active>true</active>
        <description>Recordtype for converted Prospects of type Trustee</description>
        <label>Trustee Acquisition</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

Custom--app/main/default/classes/CompletePipelineRequiredFieldsController.cls
public with sharing class CompletePipelineRequiredFieldsController {

	// Error Handling Variable
    public Boolean invalidRecord {get; private set;}
    public Property_Opportunity__c pipeline {get; set;}

    public Boolean saveError {get; private set;}

	public CompletePipelineRequiredFieldsController(ApexPages.StandardController ctrl) {
		invalidRecord = false;
		if(ctrl != null) {
			Id pipelineId = ctrl.getId();

			pipeline = (Property_Opportunity__c)Utility.selectStar(pipelineId);
			updateFieldNames();
		}
		else {
			invalidRecord = true;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Page called from invalid source.'));
		}
	}

	public List<String> nullFieldNames 	{get; private set;}
	public List<String> allFieldNames 	{get; private set;}

	// Map of Field Name with the field describe
	private static Map<String, Schema.SObjectField> fieldMap = Schema.SObjectType.Property_Opportunity__c.fields.getMap();

	private void updateFieldNames() {
		try {
			nullFieldNames = new List<String>();
			allFieldNames = new List<String>();

			//Create a set to hold fields name
	        Set<String> reqFields = new Set<String>();
	        Set<String> reqFieldsForTrustee = new Set<String>();
	        Set<String> reqFieldsForNonTrustee = new Set<String>();

	        //Create a list of Configuration_Manager__c
	        List<Configuration_Manager__c> configs = new List<Configuration_Manager__c>();
	        configs.addAll(Constants.getConfigManagerByParameterKey(Constants.APPROVAL_REQUIRED_FIELD_FOR_PIPELINE));
	        configs.addAll(Constants.getConfigManagerByParameterKey(Constants.APPROVAL_REQUIRED_FIELD_FOR_TRUSTEE_PIPELINE));
	        configs.addAll(Constants.getConfigManagerByParameterKey(Constants.APPROVAL_REQUIRED_FIELD_FOR_NON_TRUSTEE_PIPELINE));

	        //Get all the required fields from Configuration Manager
	        for(Configuration_Manager__c config : configs) {

	            //Add field in set
	            if(fieldMap.containsKey(config.Parameter_Value__c.toLowerCase())) {
				    //Add in reqFields
				    if(Constants.APPROVAL_REQUIRED_FIELD_FOR_PIPELINE.equalsIgnoreCase(config.Parameter_Key__c))
                    	reqFields.add(config.Parameter_Value__c.toLowerCase());
                    else if(Constants.APPROVAL_REQUIRED_FIELD_FOR_TRUSTEE_PIPELINE.equalsIgnoreCase(config.Parameter_Key__c))
                    	reqFieldsForTrustee.add(config.Parameter_Value__c.toLowerCase());
                	else if(Constants.APPROVAL_REQUIRED_FIELD_FOR_NON_TRUSTEE_PIPELINE.equalsIgnoreCase(config.Parameter_Key__c))
                    	reqFieldsForNonTrustee.add(config.Parameter_Value__c.toLowerCase());
	            }
	        }

	        updateFieldLists(reqFields);
	        // This condition is Bid Type = TRUSTEE
            if(Constants.BID_TYPE_TRUSTEE.equalsIgnoreCase(pipeline.Bid_Type__c)) {
            	updateFieldLists(reqFieldsForTrustee);
            }
            // This condition is Bid Type != TRUSTEE
            else if(!Constants.BID_TYPE_TRUSTEE.equalsIgnoreCase(pipeline.Bid_Type__c)) {
            	updateFieldLists(reqFieldsForNonTrustee);
            }

            nullFieldNames.sort();
            allFieldNames.sort();
		}
		catch(Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Following exception occurred: ' + e.getMessage()));
		}
	}

	private void updateFieldLists(Set<String> fieldSet) {
		//check for all the fields
	    for(String field : fieldSet) {
	    	Schema.DescribeFieldResult fieldDescribe = fieldMap.get(field).getDescribe();
	    	if(fieldDescribe.isAccessible() && fieldDescribe.isUpdateable()) {
		        allFieldNames.add(field);
		    	//Check for the pipeline data
		        if(pipeline.get(field) == null)
		            nullFieldNames.add(field);
		    }
	    }
	}

	public String pipelineSaveStatus {
		get {
			if(pipelineSaveStatus == null) {
				pipelineSaveStatus = 'SAVE_NOT_CALLED';
			}
			return pipelineSaveStatus;
		}
		private set;
	}

	public void savePipeline() {
		try {
			saveError = false;
			update pipeline;
			pipelineSaveStatus = 'SAVE_SUCCESSFUL';
		}
		catch(Exception e) {
			saveError = true;
			pipelineSaveStatus = 'SAVE_ERROR';
		}
	}

	public Boolean showAllFields {
		get {
			if(showAllFields == null)
				showAllFields = false;
			return showAllFields;
		}
		set;
	}

	public void toggleFieldsToShow() {
		showAllFields = !showAllFields;
	}
}