mdapi/Custom/objects/Configuration_Manager__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SkipTriggersForUser; Residence, Prospect, Pipeline, and Portfolio settings.</description>
    <fields>
        <fullName>Parameter_Value__c</fullName>
        <label>Parameter Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration Manager</label>
</CustomObject>

mdapi/Custom/objects/Property__c.object
<CustomObject>
    <description>This is the output of the Acquisition reporting process and is the primary &quot;purchase record&quot; of all of our properties.</description>
    <fields>
        <fullName>AC_or_Evap__c</fullName>
        <formula>TEXT(Residence__r.AC_or_Evap__c)</formula>
        <label>AC or Evap</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Baths__c</fullName>
        <formula>Residence__r.Baths__c</formula>
        <label>Baths</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bedrooms__c</fullName>
        <formula>Residence__r.Bedrooms__c</formula>
        <label>Bedrooms</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parking__c</fullName>
        <formula>TEXT(Residence__r.Parking__c)</formula>
        <label>Parking</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Code__c</fullName>
        <externalId>true</externalId>
        <label>Property Code (Asset Number)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Portfolio</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Square_Feet__c</fullName>
        <formula>Residence__r.Square_Feet__c</formula>
        <label>Square Feet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Residence__c.object
<CustomObject>
    <description>This is the &quot;parent&quot; account of all Portfolio records and represents a property address.</description>
    <fields>
        <fullName>AC_or_Evap__c</fullName>
        <label>AC or Evap</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>Evap</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address_Unit__c</fullName>
        <description>If this residence is a condo or a member of a Multi-Unit-Complex, this field holds the Unit/Flat/Suite/etc.</description>
        <inlineHelpText>If this residence is a condo or a member of a Multi-Unit-Complex, this field holds the Unit/Flat/Suite/etc.  Note that when this Residence is a member of a Multi-Unit-Complex, we will append the unit to the end of the APN to create the APN_Unique value.</inlineHelpText>
        <label>Unit</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Baths__c</fullName>
        <label>Baths</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bedrooms__c</fullName>
        <label>Bedrooms</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Child_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This residence is a &quot;Child Unit&quot; only if it belongs to a multi-unit complex such as a duplex, or a Three-Flat, or apartment building.</inlineHelpText>
        <label>Child-Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This points to the Portfolio record that was most recently linked to this residence.</inlineHelpText>
        <label>Current Portfolio</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Residences Where Current</relationshipLabel>
        <relationshipName>ResidencesWhereCurrent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Parent Residence is the multi-unit property that contains several child units, including this one, such as a duplex or triplex</description>
        <inlineHelpText>The Parent Residence is the multi-unit property that contains several child units, including this one, such as a duplex or triplex</inlineHelpText>
        <label>Parent Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Child Residences</relationshipLabel>
        <relationshipName>Child_Residences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Structure__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this Residence is comprised of other child Residences (like a Duplex, Triplex, 3-Flat, etc) then this box should be checked.</inlineHelpText>
        <label>Parent Structure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parking__c</fullName>
        <label>Parking</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 Car Garage</fullName>
                </value>
                <value>
                    <fullName>2 Car Garage</fullName>
                </value>
                <value>
                    <fullName>3 Car Garage</fullName>
                </value>
                <value>
                    <fullName>4 Car Garage</fullName>
                </value>
                <value>
                    <fullName>4+ Car Garage</fullName>
                </value>
                <value>
                    <fullName>1 Car Carport</fullName>
                </value>
                <value>
                    <fullName>2 Car Carport</fullName>
                </value>
                <value>
                    <fullName>3 Car Carport</fullName>
                </value>
                <value>
                    <fullName>No Parking</fullName>
                </value>
                <value>
                    <fullName>Slab</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Square_Feet__c</fullName>
        <label>Square Feet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Residence</label>
    <nameField>
        <displayFormat>RES-{00000}</displayFormat>
        <label>Residence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/classes/PortfolioCloneController.cls
public with sharing class PortfolioCloneController {

	// Parent Residence Reference
	public Residence__c ParentResidence {get; set;}
	// Current Residence
	public Residence__c currResidence {get; set;}
	// Child Residences
	public Residence__c[] childResidences {get; set;}
	// Portfolio Record
	public Property__c portfolio {get; set;}

	// Boolean value to check if the Portfolio has a Parent Residence or not.
	public Boolean hasParentResidence {get; set;}

	// Set to true if the page is called without residence id or from a child Residence
	public Boolean invalidRecord {get; set;}

	// Constructor
	public PortfolioCloneController(ApexPages.StandardController stdController) {
		try {
			invalidRecord = false;
			hasParentResidence = false;
			childResidences = new List<Residence__c>();

			// Check if the user belongs to the Asset manager group
			if(!Utility.userBelongsToAssetManagerGroup()) {
				invalidRecord = true;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have permissions to clone the portfolio.'));
				return;
			}

			// Throw error if no parameter is passed.
			if(stdController == null || stdController.getId() == null) {
				invalidRecord = true;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No Portfolio record passed to the page.'));
				return;
			}

			// Get the portfolio details
			portfolio = (Property__c)Utility.selectStar(stdController.getId());

			// If the portfolio has no residence, throw error
			if(portfolio.Residence__c == null) {
				invalidRecord = true;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No Residence record associated with the Portfolio.'));
				return;
			}

			// Get the residence details
			parentResidence = (Residence__c)Utility.selectStar(portfolio.Residence__c);
			// Add Address unit to the unique Address units
			uniqueUnits.add(parentResidence.Address_Unit__c);

			// if the Residence is a child Unit, create a clone of it.
			if(parentResidence.Child_Unit__c && parentResidence.Parent_Residence__c != null) {
				currResidence = parentResidence.clone(false);

				// Nullify fields to ignore
				for(String field : fieldsToIgnore) {
					currResidence.put(field, null);
				}

				// Get the Parent Residence details
				parentResidence = (Residence__c)Utility.selectStar(currResidence.Parent_Residence__c);
				// Get the Child Residences
				for(Residence__c res : [Select Name, Bedrooms__c, Baths__c, Square_Feet__c, Address_Unit__c, Parking__c, AC_or_Evap__c,
													Current_Portfolio__c, Current_Portfolio__r.Property_Code__c
													from Residence__c
													where Parent_Residence__c = :parentResidence.Id
													and   Child_Unit__c = true]) {
					childResidences.add(res);
					uniqueUnits.add(res.Address_Unit__c);
				}

				hasParentResidence = true;
			}
			else {
				// This means that the Portfolio doesnt has a parent residence.
				currResidence = parentResidence.clone(false);

				// Nullify fields to ignore
				for(String field : fieldsToIgnore) {
					parentResidence.put(field, null);
				}
			}
		}
		catch(Exception e) {
			invalidRecord = true;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Following exception occurred on the page. ' + e.getMessage()));
		}
	}

	// Set to hold all the unique units
	private Set<String> uniqueUnits = new Set<String>();	// String to store the existing the Units.

	// Function to clone the portfolio
	public PageReference clonePortfolio() {
		// Create a savepoint
		Savepoint sp = Database.setSavepoint();
		try {
			if(currResidence != null) {
				// Check if the Address Unit is a duplicate.
				if(currResidence.Address_Unit__c == null || currResidence.Address_Unit__c == '' || uniqueUnits.contains(currResidence.Address_Unit__c)) {
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Address Unit is required and must be unique.'));
					return null;
				}
			}

			PageReference pg;

			if(hasParentResidence) {
				// If there is a parent residence,
				// Insert the new Residence, clone the portfolio and associate it with the new residence.

				currResidence.Parent_Residence__c = parentResidence.Id;
				currResidence.Child_Unit__c = true;
				currResidence.Parent_Structure__c = false;

				insert currResidence;

				Property__c newProp = (Property__c)portfolio.clone(false);
				newProp.Residence__c = currResidence.Id;
				newProp.Property_Code__c = PropertyTriggerHelper.getPropertyCode(newProp);

				insert newProp;

				pg = new PageReference('/apex/PortfolioClone?id=' + newProp.Id);
			}
			else {
				// If parent residence is not present
				// Update the parent residence with the Parent structure as true
				// and insert the new child residence. Link the Portfolio to this new residence.

				parentResidence.Parent_Structure__c = true;
				parentResidence.Child_Unit__c = false;
				update parentResidence;

				currResidence.Child_Unit__c = true;
				currResidence.Parent_Structure__c = false;
				currResidence.Parent_Residence__c = parentResidence.Id;
				insert currResidence;

				portfolio.Residence__c = currResidence.Id;
				update portfolio;

				pg = new PageReference('/apex/PortfolioClone?id=' + portfolio.Id);
			}

			pg.setRedirect(true);
			return pg;
		}
		catch(Exception e) {
			Database.rollback(sp);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Following exception occurred on the page. ' + e.getMessage()));
		}
		return null;
	}

	// Get the list of Fields To Ignore from the Custom Settings
	private static Set<String> fieldsToIgnore {
		get {
			if(fieldsToIgnore == null) {
				fieldsToIgnore = new Set<String>();

				//Configuration_Manager__c
				List<Configuration_Manager__c> configs = Constants.getConfigManagerByParameterKey('ResidenceCloneIgnoreFields');

				//fill set from custom settings
		    	for(Configuration_Manager__c config : configs) {
					if(config.Parameter_Value__c != null) {
		        		fieldsToIgnore.add(config.Parameter_Value__c.trim().toLowerCase());
					}
		        }
			}
			return fieldsToIgnore;
		}
		private set;
	}
}