mdapi/Custom/objects/Disposition__c.object
<CustomObject>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Disposition Rehab</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Only Disposition Rehab should be associated with Disposition record</errorMessage>
            <filterItems>
                <field>Rehab__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Disposition</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Disposition</relationshipLabel>
        <relationshipName>Disposition</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disposition</label>
    <nameField>
        <displayFormat>DISPO-{000000}</displayFormat>
        <label>Disposition No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disposition</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Listing__c.object
<CustomObject>
    <description>This is part of the Leasing/Marketing deployment.  Tracks all key details and workflow related to homes on the market.  There are Triggers between Listing and Application Tracking that update Status fields on both records.  Use SkipTriggersForUser when doing any data updates to Listing or Application Tracking.</description>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>If the Primary Application Tracking record is populated, the Listing will move through the Status updates automatically via one or more Triggers created by Appirio in early 2013.  There are also these Workflow Rules on Application Tracking that work in conjunction with these Triggers:  (1) Update App Status When Lease is Prepared, and (2) Update App Status when Deposit Received.  Use SkipTriggersForUser for any data updates to Application Tracking or Listing.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Down (In Rehab)</fullName>
                    <default>true</default>
                    <label>Down (In Rehab)</label>
                </value>
                <value>
                    <fullName>Down - Application Pending</fullName>
                </value>
                <value>
                    <fullName>Down - Application Approved</fullName>
                </value>
                <value>
                    <fullName>Down - Preleased</fullName>
                </value>
                <value>
                    <fullName>Down - Pre-Marketing</fullName>
                </value>
                <value>
                    <fullName>OTM - Ready to List</fullName>
                </value>
                <value>
                    <fullName>OTM - Active Listing</fullName>
                </value>
                <value>
                    <fullName>OTM - Application Pending</fullName>
                </value>
                <value>
                    <fullName>OTM - Application Approved</fullName>
                </value>
                <value>
                    <fullName>OTM - Pending Deposit</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>HOLD - Currently Not Leasable</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Down - Pending Hold Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property__c.object
<CustomObject>
    <description>This is the output of the Acquisition reporting process and is the primary &quot;purchase record&quot; of all of our properties.</description>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to track the rehab record related to the portfolio</description>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Portfolio</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab__c.object
<CustomObject>
    <description>This is the central record for the Rehab deployment.  Tracks all key details relating to the Rehab process.</description>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notice_Date__c</fullName>
        <formula>Renewal__r.Lease__r.Notice_Date__c</formula>
        <inlineHelpText>Located on the Renewal record.</inlineHelpText>
        <label>Notice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <formula>TEXT( Renewal__r.Renewal_Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal</label>
        <referenceTo>Renewal__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>DO NOT MAKE ANY CHANGES TO THIS FIELD WITHOUT MAKING CORRESPONDING CHANGES TO REHAB STATUS FIELD.</description>
        <label>Rehab Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Notification Received</fullName>
                </value>
                <value>
                    <fullName>Ready to Schedule MOI/Utility Transfer</fullName>
                </value>
                <value>
                    <fullName>Move Out Scheduled</fullName>
                </value>
                <value>
                    <fullName>Move Out Assigned</fullName>
                </value>
                <value>
                    <fullName>Re-key Ready</fullName>
                    <default>true</default>
                    <label>Re-key Ready</label>
                </value>
                <value>
                    <fullName>Move Out Complete/Needs Final Budget</fullName>
                </value>
                <value>
                    <fullName>Sent to Locksmith</fullName>
                </value>
                <value>
                    <fullName>Re-key Complete</fullName>
                </value>
                <value>
                    <fullName>Budget/Depo Finalized/Needs Vendors</fullName>
                </value>
                <value>
                    <fullName>Front-End Assigned</fullName>
                </value>
                <value>
                    <fullName>Needs Final Budget</fullName>
                </value>
                <value>
                    <fullName>Needs Vendors</fullName>
                </value>
                <value>
                    <fullName>Needs GC</fullName>
                </value>
                <value>
                    <fullName>GC Awarded</fullName>
                </value>
                <value>
                    <fullName>2 Day Walk Complete</fullName>
                </value>
                <value>
                    <fullName>Five Day Complete</fullName>
                </value>
                <value>
                    <fullName>QC Assigned</fullName>
                </value>
                <value>
                    <fullName>QC Open</fullName>
                </value>
                <value>
                    <fullName>QC Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed - Completed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Rehab Needed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>HOLD - Personal Property</fullName>
                </value>
                <value>
                    <fullName>HOLD - Utilities</fullName>
                </value>
                <value>
                    <fullName>HOLD - BK</fullName>
                </value>
                <value>
                    <fullName>HOLD - Deed</fullName>
                </value>
                <value>
                    <fullName>HOLD - Occupied/TIP</fullName>
                </value>
                <value>
                    <fullName>HOLD - Other</fullName>
                </value>
                <value>
                    <fullName>HOLD - Permits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status is changed to Red or Yellow automatically based on estimated completion date.</inlineHelpText>
        <label>Delete_RYG Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                    <default>true</default>
                    <label>Green</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rehab</label>
    <nameField>
        <displayFormat>RHB-{0000}</displayFormat>
        <label>Rehab Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehabs</pluralLabel>
    <recordTypes>
        <fullName>Disposition</fullName>
        <active>true</active>
        <description>Used for Rehab Disposition</description>
        <label>Disposition</label>
    </recordTypes>
    <recordTypes>
        <fullName>Post_Acquisition_TIP</fullName>
        <active>true</active>
        <label>Post Acquisition – Purchased Rented</label>
    </recordTypes>
    <recordTypes>
        <fullName>Turn</fullName>
        <active>true</active>
        <description>Used for Rehab Turns</description>
        <label>Turn</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Renewal__c.object
<CustomObject>
    <description>For Data Loads, match on the HMYref field (preferable) or the Case Safe ID field.  This is part of the planned PM deployment.  Tracks key workflow related to the renewal process.</description>
    <fields>
        <fullName>Lease__c</fullName>
        <label>Lease</label>
        <referenceTo>Tenant_Card__c</referenceTo>
        <relationshipLabel>Renewal Record</relationshipLabel>
        <relationshipName>Lease_Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <label>Renewal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Lease Renewed</fullName>
                    <color>#78C953</color>
                    <label>Lease Renewed</label>
                </value>
                <value>
                    <fullName>Not Renewed - Notice</fullName>
                    <color>#E27001</color>
                    <label>Not Renewed - Notice</label>
                </value>
                <value>
                    <fullName>Not Renewed - Moved Out</fullName>
                    <color>#A845DC</color>
                    <label>Not Renewed - Moved Out</label>
                </value>
                <value>
                    <fullName>Not Renewed - Transfer to IH Property</fullName>
                    <color>#F3D904</color>
                    <label>Not Renewed - Transfer to IH Property</label>
                </value>
                <value>
                    <fullName>Lease Terminated (Eviction/Skip/Etc.)</fullName>
                    <color>#A53711</color>
                    <label>Lease Terminated (Eviction/Skip/Etc.)</label>
                </value>
                <value>
                    <fullName>Month-to-Month</fullName>
                    <color>#66E9BD</color>
                    <label>Month-to-Month</label>
                </value>
                <value>
                    <fullName>Eviction in Process</fullName>
                    <color>#0B24BE</color>
                    <label>Eviction in Process</label>
                </value>
                <value>
                    <fullName>&gt;120 Days Out</fullName>
                    <color>#419249</color>
                    <label>&gt;120 Days Out</label>
                </value>
                <value>
                    <fullName>Property - Sold</fullName>
                    <color>#0B6FCE</color>
                    <label>Property - Sold</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Renewal</label>
    <nameField>
        <displayFormat>RNWL-{00000}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Tenant_Card__c.object
<CustomObject>
    <description>This will be used at a future date to track lease details imported from Yardi.  FOR DATA LOADS, USE EITHER HMYREF OR CASESAFEID.</description>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <label>Renewal Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lease</label>
    <nameField>
        <displayFormat>LEASE{00000}</displayFormat>
        <label>Lease Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Custom--app/main/default/classes/Trigger_RenewalHelper.cls
/**
* @author Prashant Wayal
* @date 18-Feb-2015
* @description Helper class for Trigger_Renewal trigger
* @modified by : Saurabh kumar (5/27/2016) D-00015600
* Modified by : Poonam Bhargava (06/19/2017) - D-00017170
* Modified by : Saurabh Kumar (06/19/2017) - D-00017164
*/
public with sharing class Trigger_RenewalHelper{
    
    /**
    * @description Method to update renewal related rehab records 
    * @params List of Renewal Records
    */
    public static void updateRehabs(List<Renewal__c> renewalList){
        Set<String> renewalIdSet = new Set<String>();
        for(Renewal__c renewal: renewalList)
            renewalIdSet.add(renewal.Id);
            
        //Get all rehab records related to renewals and update
        List<Rehab__c> rehabList = [select Id from Rehab__c where Renewal__c IN: renewalIdSet];
        if(!rehabList.isEmpty())
            update rehabList;
    }
    
    //This method is to close cancel all open turn rehab when a new lease renewed
    public static void closeCancelRehabsOnLeaseRenewal(List<Renewal__c> newRenewalList, Map<Id, Renewal__c> oldRenewalMap) {
    
        List<Renewal__c> allowedRenewals = new List<Renewal__c>();
        
        //loop overe renewal records
        for( Renewal__c renewalObj : newRenewalList )   {
        
            if( Trigger.isUpdate 
                && renewalObj.Renewal_Status__c != null 
                && renewalObj.Renewal_Status__c.equalsIgnoreCase( Constants.RENEWAL_STATUS_LEASE_RENEWED )
                &&  renewalObj.Renewal_Status__c != oldRenewalMap.get(renewalObj.Id).Renewal_Status__c ) {
                if( renewalObj.Lease__c != null ) { 
                    allowedRenewals.add( renewalObj );
                }
            }
        }
    
        if( allowedRenewals.size() > 0 ) {
            
             // query Turn record type
            List<RecordType> rtList = [Select Id, Name, SObjectType, DeveloperName
                                        From RecordType where (DeveloperName = 'TURN' OR DeveloperName = 'Post_Acquisition_TIP' OR DeveloperName = 'Disposition')
                                        And SObjectType = 'Rehab__c' AND IsActive = true 
                                        ORDER BY DeveloperName Limit 3
                                       ];
            
            Id postAcqTIPRecordTypeId;
            Id turnRecordTypeId;
        
            for( RecordType rt : rtList ) {
                
                if( rt.DeveloperName.equalsIgnoreCase( 'TURN' )) {
                    turnRecordTypeId = rt.Id;
                }
                else if( rt.DeveloperName.equalsIgnoreCase( 'Post_Acquisition_TIP' )) {
                    postAcqTIPRecordTypeId = rt.id;
                }
            }
            
            Map<Id, Rehab__c> mapRehabToUpdate = new Map<Id, Rehab__c>();
            Map<Id, Listing__c> mapListingToUpdate = new Map<Id, Listing__c>();
            
            if( turnRecordTypeId != null ) { 
                
               // query rehabs
               Map<Id, Rehab__c> mapRehabs = new Map<Id, Rehab__c> ( [ Select Renewal__r.Lease__c,
                                                                               Listing__r.Status__c,
                                                                               Listing__c,
                                                                               Renewal__c,
                                                                               Stage__c
                                                                        From Rehab__c
                                                                        Where Renewal__c in: allowedRenewals
                                                                        And Renewal__r.Lease__r.Notice_Date__c =: NULL
                                                                        AND RecordTypeId !=: NULL
                                                                        And ( RecordTypeId =: turnRecordTypeId
                                                                              OR RecordTypeId =: postAcqTIPRecordTypeId )
                                                                        AND (   Rehab_Status__c like 'Active%' 
                                                                                OR Rehab_Status__c like 'HOLD%' )
                                                                        ] );
                                                                        
                for( Rehab__c rehabObj : mapRehabs.values() ) {
                    
                    Rehab__c rehabObjToUpdate = new Rehab__c( Id = rehabObj.Id,
                                                              Stage__c = Constants.REHAB_STAGE_CLOSED_CANCELLED  );
                                                              
                    mapRehabToUpdate.put( rehabObjToUpdate.Id, rehabObjToUpdate );
                    if( rehabObj.Listing__c != null ) {
                        mapListingToUpdate.put( rehabObj.Listing__c, 
                                                 new Listing__c( Id = rehabObj.Listing__c,
                                                                Status__c = 'Cancelled'
                                                               ));
                    }
                }
            }
                
            if( mapRehabToUpdate.size() > 0 ) {
                
                update mapRehabToUpdate.values();
                Trigger_RehabHandler.isTrigger_RehabCalld = false;
            }
            
            if( mapListingToUpdate.size() > 0 ) {
                 
                update mapListingToUpdate.values();
            }
        }
     }
    
     /**
      * @Description    :   Method for create rehab records based on renewal status.
      *
      * @arg            :   List of new renewal, map of old renewal.
      *
      * @return         :   Void
    **/
    //commented based on D-00015600 :- This method has been depricated 
 /*   public static void createRehabBasedOnRenewalStatus(List<Renewal__c> newRenewals, map<Id, Renewal__c> mapOldRenewals) {
    
        //Initialize list of rehab to be inserted
        List<Rehab__c> listOfRehabToBeInserted = new List<Rehab__c>();
        
        //Map to hold renewal records with Portfolio Id
        Map<Id, List<Renewal__c>> mapPortfolioWithRenewals= new Map<Id, List<Renewal__c>>();
        
        //Check for null
        if(newRenewals != null) {
        
            //Loop through Trigger.new
            for(Renewal__c renew : newRenewals) {
            
                //Checking and validting for eligibility and then accordingly populating the renewal map
                if(String.isNotBlank(renew.Renewal_Status__c ) && renew.Renewal_Status__c == 'Not Renewed - Notice' && 
                (mapOldRenewals == null || mapOldRenewals.get(renew.Id).Renewal_Status__c != renew.Renewal_Status__c )) {
                    
                    //Check map for key and populate accordingly
                    if(mapPortfolioWithRenewals.containsKey(renew.Id))
                        mapPortfolioWithRenewals.get(renew.Portfolio__c).add(renew);
                    else
                        mapPortfolioWithRenewals.put(renew.Portfolio__c, new List<Renewal__c>{renew});
                }
            }
            
            //Fecth the dispostion relared to Portfolio
            Map<Id, Disposition__c> mapDispostion = new Map<Id, Disposition__c>( [ Select Portfolio__c 
                                                            From Disposition__c
                                                            Where Portfolio__c IN: mapPortfolioWithRenewals.keySet()
                                                            And BX_Approval_of_Sale__c = 'Yes'
                                                            And IH_Approval_of_Sale__c = 'Yes'
                                                            ] );
                                                                        
                                                                   
            Map<Id, Disposition__c> mapPortfolioIdToDispostion = new Map<Id, Disposition__c>();
            for( Disposition__c dis : mapDispostion.values() ) {
                mapPortfolioIdToDispostion.put( dis.Portfolio__c, dis );
            }
            
            //Checking for map size
            if(mapPortfolioWithRenewals.size() > 0 ) {
                
                //Initialize Map of portfolios and populate 
                Map<Id, Property__c> mapPortfolios = new Map<Id, Property__c>([SELECT ID, Residence__c From Property__c 
                                                                               Where Id IN : mapPortfolioWithRenewals.keyset()]);
                
                //Retrieve record from record type
                List<RecordType> listRecordType = [Select Id from RecordType Where SObjectType = 'Rehab__c' And DeveloperName = 'Disposition' And isActive = True];
                
                //Check for  Record Type list size
                if(listRecordType.size() > 0) {
                    
                    //Loop through keyset
                    for(Id propId : mapPortfolioWithRenewals.keySet()) {
                    
                        //Check for id in map
                        if(mapPortfolioWithRenewals.containsKey(propId) && mapPortfolioIdToDispostion.containsKey(propId)) {
                            
                            //Loop through Renewal
                            for(Renewal__c renewal : mapPortfolioWithRenewals.get(propId)) {
                            
                                //Populate Rehab record and add to list
                                listOfRehabToBeInserted.add(new Rehab__c(RecordTypeId = listRecordType[0].Id, 
                                                                            Stage__c= 'Notification Received', 
                                                                            Home__c = mapPortfolios.get(propId).Residence__c,
                                                                            Portfolio__c = propId));
                            }
                        }
                    }
                }
            }
            
            //Check for rehab list size and insert 
            if(listOfRehabToBeInserted.size() > 0)
                insert listOfRehabToBeInserted; 
        }   
    }*/
    
    // Saurabh Kumar - (5/24/2017) - D-00017164
    public static void updateListingWhenLeaseRenewed(List<Renewal__c> listRenewal ,Map<Id, Renewal__c> oldMap){
        // 5/24/2017 : new renewed lease updated , renewal status change to Lease Renewed or Month to Month
        // Check if it is related to any listing or rehab then pass rehab Id to method cancelRehabAndListing
        
        Set<Id> renewalIds = new Set<Id>();
        Map<Id,Id> mapRehabwithListingIds = new Map<Id,Id>();
        
        for(Renewal__c renewal : listRenewal){
            if((Utility.hasFieldChanged(renewal, oldMap, 'New_Renewed_Lease__c') && renewal.New_Renewed_Lease__c != null) 
                || (Utility.hasFieldChanged(renewal, oldMap, 'Renewal_Status__c') 
                    && (renewal.Renewal_Status__c == constants.RENEWAL_STATUS_LEASE_RENEWED 
                         || renewal.Renewal_Status__c == constants.RENEWAL_STATUS_MONTH_TO_MONTH)))
            {
                renewalIds.add(renewal.Id);
            }
        }
        
        System.debug('** Renewal Ids ** '+renewalIds);
        
        if(renewalIds.isEmpty())
            return;
            
        for(Rehab__c rehab : [Select Id, listing__c from rehab__c where Renewal__c in : renewalIds and 
                                (stage__c !=: Constants.REHAB_STAGE_CLOSED_CANCELLED or 
                                 listing__r.status__c !=: Constants.CANCELLED)])
        {
            mapRehabwithListingIds.put(rehab.id, rehab.listing__c);
            System.debug('** Map Rehab/Listing Ids ** '+mapRehabwithListingIds);
        }
        
        
        
        if(!mapRehabwithListingIds.isEmpty()){
            LeaseTriggerHelper.cancelRehabAndListing(mapRehabwithListingIds);
        }
    }

    //Added by Poonam Bhargava (06/19/2017)- D-00017170
    /**
      * @Description    :   Method to populate Renewal Coordinator on related 'New (Renewed) Lease'.
      *
      * @arg            :   List<Renewal__c> newRenewals, map<Id, Renewal__c> mapOldRenewals.
      *
      * @return         :   Void
    **/
    public static void populateRenewalCoordinatorOnLease(List<Renewal__c> newRenewals, map<Id, Renewal__c> mapOldRenewals) {
    
        //Map to hold Lease Id with Lease record
        Map<Id, Tenant_Card__c> mapOfLease = new Map<Id, Tenant_Card__c>();
        
        //Loop Over Renewal records (check for insert/update/delete case)
        for(Renewal__c re : newRenewals != null ? newRenewals :  mapOldRenewals.values()) {
            
            //Check the criteria for insert condition and populate Lease map accordingly
            if(mapOldRenewals == null && re.New_Renewed_Lease__c != null)
                mapOfLease.put(re.New_Renewed_Lease__c, new Tenant_Card__c(Id = re.New_Renewed_Lease__c, Renewal_Coordinator__c = null));
            
            //Check the eligible criteria for update when 'New (Renewed) Lease' or 'Renewal Coordinator / APM' field is updated
            if(newRenewals != null && mapOldRenewals != null && (re.New_Renewed_Lease__c != mapOldRenewals.get(re.Id).New_Renewed_Lease__c 
                                                                    || re.Renewal_Coordinator__c != mapOldRenewals.get(re.Id).Renewal_Coordinator__c)) {
                
                //Check whether New (Renewed) Lease is not null and populate lease map accordingly
                if(re.New_Renewed_Lease__c != null)
                    mapOfLease.put(re.New_Renewed_Lease__c, new Tenant_Card__c(Id = re.New_Renewed_Lease__c, Renewal_Coordinator__c = null));
                
                //Check field New (Renewed) Lease is updated from not null to null value and populate map
                if(mapOldRenewals.get(re.Id).New_Renewed_Lease__c != null)
                    mapOfLease.put(mapOldRenewals.get(re.Id).New_Renewed_Lease__c, new Tenant_Card__c(Id = mapOldRenewals.get(re.Id).New_Renewed_Lease__c, Renewal_Coordinator__c = null));
            }
            
            //Delete case when field 'New (Renewed) Lease' is removed and populate map accordingly
            if(newRenewals == null && re.New_Renewed_Lease__c != null)
                mapOfLease.put(re.New_Renewed_Lease__c, new Tenant_Card__c(Id = re.New_Renewed_Lease__c, Renewal_Coordinator__c = null));   
        }   
        
        //Check for map mapOfLease size
        if(mapOfLease.size() > 0){
            
            //Retrieve Lease records with the child Renewal records
            for(Tenant_Card__c tC : [Select Id, Renewal_Coordinator__c, 
                                        (Select Id, Renewal_Coordinator__c from Renewals__r order by LastModifiedDate DESC LIMIT 1) 
                                        from Tenant_Card__c where Id IN : mapOfLease.keySet()]){

                //Check for child (Renewal) record size, lease as key in the map and populate Lease map with values accordingly
                if(tC.Renewals__r.size() > 0 && mapOfLease.containsKey(tC.Id))
                    mapOfLease.get(tC.Id).Renewal_Coordinator__c = tC.Renewals__r[0].Renewal_Coordinator__c;    
            }
        }
        
        //Check for map size and perform update operation on map
        if(mapOfLease.size() > 0 ){
            
            //Bypass Lease trigger
            LeaseTriggerHelper.EXECUTE_LEASE_TRIGGER = false;
            
            //Update Lease records
            update mapOfLease.values(); 
            
            //Set flag as true to keep on the lease trigger
            LeaseTriggerHelper.EXECUTE_LEASE_TRIGGER =  true;
        }
                  
    } 
}