mdapi/Custom/objects/File_Storage_Record__c.object
<CustomObject>
    <description>This holds metadata about files that are uploaded into
		external systems (Box/S3/StructuredFN)</description>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Type__c</fullName>
        <description>Corresponds to which folder the document belongs,not  &quot;Content Type&quot; as in PDF or Text or Doc</description>
        <label>File Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Export_Date__c</fullName>
        <label>Last Export Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>File Storage Records</relationshipLabel>
        <relationshipName>File_Storage_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF(
	NOT(ISBLANK(Property__c )),
	TEXT(Property__r.Region__c),
	IF(
		NOT(ISBLANK( Rehab__c )),
		Rehab__r.Region__c,
		IF(
			NOT(ISBLANK(HD_Budget_Walk__c)),
			HD_Budget_Walk__r.Region__c,
			&quot;&quot;
		)	
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Path_Name__c</fullName>
        <description>Full Path of the S3 file--Includes file name</description>
        <externalId>true</externalId>
        <label>S3 Path Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>File Storage Record</label>
    <nameField>
        <displayFormat>FSR-{00000}</displayFormat>
        <label>File Storage Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Storage Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/File_Storage_Type__c.object
<CustomObject>
    <description>This will be used as part of the File Storage (S3) application.</description>
    <fields>
        <fullName>Allowed_For_Objects__c</fullName>
        <label>Allowed For Objects</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Disposition__c</fullName>
                </value>
                <value>
                    <fullName>HD_Budget_Walk__c</fullName>
                </value>
                <value>
                    <fullName>Property__c</fullName>
                </value>
                <value>
                    <fullName>Rehab__c</fullName>
                </value>
                <value>
                    <fullName>Residence__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_To_SFN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether files of this type should be uploaded to Structured FN</description>
        <inlineHelpText>Whether files of this type should be uploaded to Structured FN.  Note that this only works for Portfolio docs, and care should be taken so that only the docs that our lender cares about are uploaded.</inlineHelpText>
        <label>Upload To SFN</label>
        <type>Checkbox</type>
    </fields>
    <label>File Storage Type</label>
    <nameField>
        <label>File Storage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Storage Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property__c.object
<CustomObject>
    <description>This is the output of the Acquisition reporting process and is the primary &quot;purchase record&quot; of all of our properties.</description>
    <fields>
        <fullName>Fund__c</fullName>
        <description>Initialize any portfolio record whose create Date &lt; FTD (4/3/2013) to &quot;01&quot;
Any portfolio record created thereafter (whose create Date &gt;= FTD) needs to have its Fund set by porting from Pipeline object</description>
        <inlineHelpText>This field is editable only by a System Administrator.  Please submit an SF Request to have it changed.</inlineHelpText>
        <label>Fund</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>This field maps to the Market2 value in the Yardi Integration file, &quot;AttributesMarket&quot;.  The similar Market field is derived via a Custom Setting called Yardi Short Region Config.</description>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region__c.object
<CustomObject>
    <description>Captures the records for regions.  Some of the values are used in one or more Triggers that auto-populate fields on Prospect and/or Pipeline and/or Portfolio records.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Custom--app/main/default/classes/PortfolioFileExportController.cls
/**
 *   Description  :  Controller Class for VFP PortfolioFileExport
 *
 *   Created By Shrinath
 *
 *   Created Date:  01/23/2014
 *
 *   Revision Logs:  V1.0 - Created
 **/
public without sharing class PortfolioFileExportController {

	// Get the List of Regions
	public List<SelectOption> regionOptions {
		get {
			if(regionOptions == null) {
				regionOptions = new List<SelectOption>();
				regionOptions.add(new SelectOption('', 'Select'));
				for(Region__c region : [Select Name from Region__c order by Name])
					regionOptions.add(new SelectOption(region.Name, region.Name));
			}
			return regionOptions;
		}
		private set;
	}

	// Get the List of File Storage Types
	public List<SelectOption> fileStrTypeOptions {
		get {
			if(fileStrTypeOptions == null) {
				fileStrTypeOptions = new List<SelectOption>();
				fileStrTypeOptions.add(new SelectOption('', 'Select'));
				// Get all the File Types for Property
				for(File_Storage_Type__c fileStrType : [SELECT Name FROM File_Storage_Type__c
																	WHERE Upload_To_SFN__c = true
																	AND Allowed_For_Objects__c INCLUDES ('Property__c')
																	order by Name])
					fileStrTypeOptions.add(new SelectOption(fileStrType.Name, fileStrType.Name));
			}
			return fileStrTypeOptions;
		}
		private set;
	}

	public String fund {get; set;}
	public String region {get; set;}
	public String fileStrType {get; set;}

	// Constructor
	public PortfolioFileExportController() {

		// Get the values from the Query String parameters
		fund = VFUtil.getPageParameter('fund');
		region = VFUtil.getPageParameter('region');
		fileStrType = VFUtil.getPageParameter('fileStrType');
		// when fileStrType is null , fund == null so that it is defaulted only when user comes on page first time not when he clicks on search
		if(  fileStrType == null && fund == null ) {
			fileStrType = 'Lease Agreement';
		}

		//showMarkDelivered = false;
	}

	// Function to search the records
	public PageReference searchRecords() {
		// Show error message if any of the filter selected is blank
		if(String.isBlank(fund)) {
			VFUtil.AddErrorMessage('Fund is required for all searches.');
			return null;
		}
		fileStrRecordList = null;
		return getCurrentPageReference();
	}

	public PageReference getCurrentPageReference() {
		// Add the paramters to page and recall the page.
		PageReference pg = Page.PortfolioFileExport;
		pg.getParameters().put('fund', fund);
		pg.getParameters().put('region', region);
		pg.getParameters().put('fileStrType', fileStrType);

		pg.setRedirect(true);
		return pg;
	}

	public Integer totalSize {get; set;}

	// Variable to Get the File Storage records in a wrapper class
	public List<FileStorageRecordWrapper> fileStrRecordList {
		get {
			if(fileStrRecordList == null) {
				//showMarkDelivered = false;
				totalSize = 0;
				fileStrRecordList = new List<FileStorageRecordWrapper>();
				// Get records only if all the filter criterias are selected
				if(String.isNotBlank(fund)) {

					String query = 'Select Name, File_Name__c, S3_Path_Name__c, File_Type__c, Property__c, Property__r.Region__c, Property__r.Fund__c from 	File_Storage_Record__c';
						  query += ' where Property__c != null '
						  		   + ' and Last_Export_Date__c = null';
					if(String.isNotBlank(fund))
						query += ' and Property__r.Fund__c = :fund';
					if(String.isNotBlank(region))
						query += ' and Property__r.Region__c = :region';
					if(String.isNotBlank(fileStrType))
						query += ' and File_Type__c = :fileStrType';
					query += ' order by Property__r.Region__c, File_Type__c, File_Name__c desc limit 49900';

					List<File_Storage_Record__c> fileStrRecords = (List<File_Storage_Record__c>)Database.query(query);
					if(fileStrRecords != null && !fileStrRecords.isEmpty()) {
						// Get the S3 Url for the files from the helper function
						totalSize = fileStrRecords.size();
						Map<Id, String> mapFSR_s3RequestUrl = IHS3IntegrationServiceEnh.getS3FileUrlMap(fileStrRecords, fileStrRecords[0].Property__c);
						// Add the records to the wrapper list
						for(File_Storage_Record__c fileStrRec : fileStrRecords) {
							String s3Url = (mapFSR_s3RequestUrl.containsKey(fileStrRec.Id)) ? mapFSR_s3RequestUrl.get(fileStrRec.Id) : '';
							fileStrRecordList.add(new FileStorageRecordWrapper(fileStrRec, s3Url));
							if(fileStrRecordList.size() == 200)
								break;
						}
					}
				}

			}
			return fileStrRecordList;
		}
		set;
	}

	// Function to get the File Recors size
	public Integer getFileStrRecordsSize() {
		return (fileStrRecordList != null) ? fileStrRecordList.size() : 0;
	}

	// Wrapper class
	public class FileStorageRecordWrapper {
		public File_Storage_Record__c fileStrRec {get; set;}
		public Boolean errOnUpload {get; set;}
		public String s3Url {get; set;}

		// Constructor
		public FileStorageRecordWrapper(File_Storage_Record__c fileStrRec, String s3Url) {
			this.fileStrRec = fileStrRec;
			this.s3Url = s3Url;
			errOnUpload = false;
		}
	}

	// Function to Mark Deliver the files
	public PageReference markDelievered() {

		List<File_Storage_Record__c> fileStrRecordsForUpdate = new List<File_Storage_Record__c>();
		for(FileStorageRecordWrapper fileStrRecWrap : fileStrRecordList) {
			File_Storage_Record__c temp = fileStrRecWrap.fileStrRec;
			// If error, add error message else add the Uploaded date
			if(!fileStrRecWrap.errOnUpload)
				temp.Last_Export_Date__c = System.today();

			fileStrRecordsForUpdate.add(temp);
		}

		try {
			// Update the file storage records
			update fileStrRecordsForUpdate;
			return getCurrentPageReference();
		}
		catch(Exception e) {
			VFUtil.AddErrorMessage('Following error occurred: ' + e.getMessage());
		}
		return null;
	}

}