mdapi/Custom/objects/GL_Code__c.object
<CustomObject>
    <fields>
        <fullName>GL_Code_Acquisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code Acquisition</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>GL Codes (GL Code Acquisition)</relationshipLabel>
        <relationshipName>GL_Codes_Acquisition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Turn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code Turn</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>GL Codes (GL Code Turn)</relationshipLabel>
        <relationshipName>GL_Codes_Turn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property_Invoice__c.object
<CustomObject>
    <description>Deployed Via Permission Set.This is a holding place to support a future state w/ rehab actuals/invoices.</description>
    <fields>
        <fullName>GL_Code_Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Type_Adjusted__c</fullName>
        <formula>IF( ISPICKVAL( Rehab__r.Type__c, &apos;Post-Acquisition&apos; ), 
IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
, GL_Code_Original__r.Name, 
GL_Code_Original__r.GL_Code_Acquisition__r.Name 
), 
IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
GL_Code_Original__r.Name, 
GL_Code_Original__r.GL_Code_Turn__r.Name 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GL Code Type Adjusted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Code__c</fullName>
        <description>IF NEW GL CODES ARE ADDED - THEY ALSO NEED TO BE ADDED TO THE CHANGE ORDER AND THE YARDI INVOICE FORMULA NEEDS TO BE UPDATED</description>
        <label>GL Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1260100 - Rehab Other</fullName>
                </value>
                <value>
                    <fullName>1260125 - Rehab Demo/Waste</fullName>
                </value>
                <value>
                    <fullName>1260140 - Rehab Pests/Termites</fullName>
                </value>
                <value>
                    <fullName>1260150 - Rehab Cleaning</fullName>
                </value>
                <value>
                    <fullName>1260175 - Rehab Initial Re-Key</fullName>
                </value>
                <value>
                    <fullName>1260200 - Rehab General Contractor</fullName>
                </value>
                <value>
                    <fullName>1260210 - Rehab GC Change Order</fullName>
                </value>
                <value>
                    <fullName>1260300 - Rehab Roofs</fullName>
                </value>
                <value>
                    <fullName>1260325 - Rehab Garage and Garage Doors</fullName>
                </value>
                <value>
                    <fullName>1260350 - Rehab Exterior Surfaces</fullName>
                </value>
                <value>
                    <fullName>1260375 - Rehab Sidewalks/Driveways</fullName>
                </value>
                <value>
                    <fullName>1260400 - Rehab Cabinets</fullName>
                </value>
                <value>
                    <fullName>1260425 - Rehab Interior Painting</fullName>
                </value>
                <value>
                    <fullName>1260450 - Rehab Flooring</fullName>
                </value>
                <value>
                    <fullName>1260475 - Rehab Door/Window Costs</fullName>
                </value>
                <value>
                    <fullName>1260480 - Rehab Blinds</fullName>
                </value>
                <value>
                    <fullName>1260500 - Rehab Countertops</fullName>
                </value>
                <value>
                    <fullName>1260600 - Rehab Landscape</fullName>
                </value>
                <value>
                    <fullName>1260700 - Rehab Pool Service Fees</fullName>
                </value>
                <value>
                    <fullName>1260710 - Rehab Pool Maintenance Costs</fullName>
                </value>
                <value>
                    <fullName>1260800 - Rehab Appliances</fullName>
                </value>
                <value>
                    <fullName>1260825 - Rehab Specialty Electric</fullName>
                </value>
                <value>
                    <fullName>1260850 - Rehab Specialty Plumbing</fullName>
                </value>
                <value>
                    <fullName>1260900 - Rehab HVAC</fullName>
                </value>
                <value>
                    <fullName>1260910 - Rehab Utilities</fullName>
                </value>
                <value>
                    <fullName>1260915 - Rehab Utilities Prior Ownership</fullName>
                </value>
                <value>
                    <fullName>1261000 - Rehab Capitalized Insurance</fullName>
                </value>
                <value>
                    <fullName>1261100 - Rehab Capitalized Tax</fullName>
                </value>
                <value>
                    <fullName>1261200 - Rehab Capitalized Interest</fullName>
                </value>
                <value>
                    <fullName>1261300 - Rehab Capitalized HOA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rehab_Projected_Spend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab Projected Spend</label>
        <referenceTo>Rehab_Projected_Spend__c</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Property Invoice</label>
    <nameField>
        <displayFormat>PropInvoice-{0000}</displayFormat>
        <label>Property Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab__c.object
<CustomObject>
    <description>This is the central record for the Rehab deployment.  Tracks all key details relating to the Rehab process.</description>
    <fields>
        <fullName>Actual_Spend_Total__c</fullName>
        <label>Actual Spend Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Projected_Spend_Changes_To_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total amount of change orders</inlineHelpText>
        <label>Change Order Running Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Projected_Spend_Running_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This number is the total of the base budget plus all change orders</inlineHelpText>
        <label>Committed Spend Running Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rehab</label>
    <nameField>
        <displayFormat>RHB-{0000}</displayFormat>
        <label>Rehab Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab_Projected_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Spend_Total__c</fullName>
        <description>This field will populate from the Property Invoice Object by GL Code</description>
        <label>Actual Spend Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Base_Budget_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Base_Budget_Reported_Timestamp__c</fullName>
        <label>Base Budget Reported Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Changes_To_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Changes To Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GL_Code_Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Type_Adjusted__c</fullName>
        <formula>IF( NOT(ISNULL(Rehab__c)) , 
      IF( ISPICKVAL( Rehab__r.Type__c, &apos;Post-Acquisition&apos; ), 
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
                      , GL_Code_Original__r.Name, 
                      GL_Code_Original__r.GL_Code_Acquisition__r.Name 
          ),
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
                      GL_Code_Original__r.Name,  
                      GL_Code_Original__r.GL_Code_Turn__r.Name ) 
        ),
      IF( OR( ISPICKVAL( HD_Budget_Walk__r.Type__c, &apos;Pre-Acquisitions&apos; ),
              ISPICKVAL( HD_Budget_Walk__r.Type__c, &apos;Post-Acquisitions&apos; ) ),   
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
                      , GL_Code_Original__r.Name, 
                      GL_Code_Original__r.GL_Code_Acquisition__r.Name 
          ),
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
                      GL_Code_Original__r.Name,  
                      GL_Code_Original__r.GL_Code_Turn__r.Name )
        )
    )</formula>
        <label>GL Code Type Adjusted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Code__c</fullName>
        <label>Obsolete GL Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Running_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Running Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rehab Projected Spend</label>
    <nameField>
        <displayFormat>RPS-{00000000}</displayFormat>
        <label>RPS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehab Projected Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/Property_InvoiceTriggerHelper.cls
/**
 *   Description  :  Helper Class for Trigger_Property_Invoice on Property_Invoice__c Object
 *
 *   Created By Shrinath
 *
 *   Created Date:  11/8/2013k
 *
 *   Revision Logs:  V1.0 - Created
 **/
public without sharing class Property_InvoiceTriggerHelper {

		/*
			Method to populate rehab projected spend
		*/
		public static void populateRehabProjectedSpend( List<Property_Invoice__c> newPropertyInvoice,
												   		Map<Id, Property_Invoice__c> oldMapPropertyInvoice ) {

			Set<String> setGLCodesTypeAdjusted = new Set<String>();
			Set<Id> setRehabIds = new Set<Id>();

			for( Property_Invoice__c piObj : newPropertyInvoice ) {

				if( piObj.GL_Code_Original__c == null ) {
					piObj.GL_Code_Original__c.addError( 'Please enter a value in GL Code' );
				}
				else {
						if( trigger.isInsert || piObj.Rehab_Projected_Spend__c == null ) {
							setRehabIds.add(piObj.Rehab__c);
							setGLCodesTypeAdjusted.add( piObj.GL_Code_Type_Adjusted__c );
						}
				}
			}

			Map<Id, Rehab__c> mapRehab = new Map<Id, Rehab__c>( [ Select RecordType.Name
															   From Rehab__c
															   Where Id =: setRehabIds
															 ]);

			// query rehab projected spend
			List<Rehab_Projected_Spend__c> listRehabProjectedSpends = [Select Id,
																			  Rehab__c,
																	          GL_Code_Original__c,
																	          GL_Code_Type_Adjusted__c
																	   From Rehab_Projected_Spend__c
																	   Where GL_Code_Type_Adjusted__c in: setGLCodesTypeAdjusted
																	   And Rehab__c in: setRehabIds];

	        Map<String, Rehab_Projected_Spend__c> mapGLCodeToRehabProjectedSpend = new Map<String, Rehab_Projected_Spend__c>();

	        Map<String, Rehab_Projected_Spend__c> mapGLCodeToRehabProjectedSpendToInsert = new Map<String, Rehab_Projected_Spend__c>();

	        for( Rehab_Projected_Spend__c rpsObj : listRehabProjectedSpends ) {

	        	String mapKey = rpsObj.Rehab__c + rpsObj.GL_Code_Type_Adjusted__c.trim().toLowerCase();
	        	mapGLCodeToRehabProjectedSpend.put( mapKey, rpsObj );

	        }

			Map<String, GL_Code__c> mapGLCodeNameToGLCode = new Map<String, GL_Code__c>();
			// Query GL Codes
			Map<Id, GL_Code__c> mapGLCode = new Map<Id, GL_Code__c>( [ Select Name,
												                              GL_Code_Acquisition__c,
												                              GL_Code_Turn__c,
												                              GL_Code_Acquisition__r.Name,
												                              GL_Code_Turn__r.Name
										                               From GL_Code__c
										                               Where Name !=: Null
										                             ]);
			for( GL_Code__c glCodeObj : mapGLCode.values() ) {
				mapGLCodeNameToGLCode.put( glCodeObj.Name.trim().toLowerCase(), glCodeObj );
			}

			for( Property_Invoice__c piObj : newPropertyInvoice ) {

			      if( piObj.GL_Code_Original__c != null
			          && piObj.Rehab__c != null
			          && piObj.Rehab_Projected_Spend__c == null ) {

		                String mapKey = piObj.Rehab__c + piObj.GL_Code_Type_Adjusted__c.trim().toLowerCase();
				        if( !mapGLCodeToRehabProjectedSpend.containsKey( mapKey ) ) {
							  Rehab__c rehab = mapRehab.get( piObj.Rehab__c );
			        	      GL_Code__c glCodeObj = mapGLCode.get( piObj.GL_Code_Original__c );
			        	      String glCodeTypeAdjusted = GL_Code_Service.getTypeAdjustedGLCode( glCodeObj, rehab );
			        	      GL_Code__c glCodeTypeAdjustedObj = mapGLCodeNameToGLCode.get( glCodeTypeAdjusted.trim().toLowerCase() );

					          mapGLCodeToRehabProjectedSpendToInsert.put( mapKey, new Rehab_Projected_Spend__c( Running_Total__c = 0,
															                                                    Rehab__c = piObj.Rehab__c,
															                                                    GL_Code_Original__c = glCodeTypeAdjustedObj.Id ) );
				        }
			      }
		    }

			insert mapGLCodeToRehabProjectedSpendToInsert.values();
			mapGLCodeToRehabProjectedSpend.putAll( mapGLCodeToRehabProjectedSpendToInsert );

			for( Property_Invoice__c piObj : newPropertyInvoice ) {

				if( piObj.GL_Code_Original__c != null
						&& piObj.Rehab__c != null
						&& piObj.Rehab_Projected_Spend__c == null ) {

	    	            String mapKey = piObj.Rehab__c + piObj.GL_Code_Type_Adjusted__c.trim().toLowerCase();
						if(mapGLCodeToRehabProjectedSpend.containsKey( mapKey ) ) {
							piObj.Rehab_Projected_Spend__c = mapGLCodeToRehabProjectedSpend.get( mapKey ).Id;
						}
				}
			}

	}

	/*
		Method to update rehab projected spend
	*/
	public static void updateRehabProjectedSpend( List<Property_Invoice__c> newPropertyInvoice,
											   	  Map<Id, Property_Invoice__c> oldMapPropertyInvoice ) {


		Set<Id> setRehabProjectedSpendIds = new Set<Id>();
		for( Property_Invoice__c piObj : newPropertyInvoice ) {

			   if( piObj.Rehab_Projected_Spend__c != null
									  &&
									  (
									  	   Utility.hasFieldChanged( piObj, oldMapPropertyInvoice, 'Invoice_Amount__c')
									  	|| Utility.hasFieldChanged( piObj, oldMapPropertyInvoice, 'Rehab_Projected_Spend__c')
									   ) ) {

					if(  trigger.isUpdate && Utility.hasFieldChanged( piObj, oldMapPropertyInvoice, 'Rehab_Projected_Spend__c') ) {
						Id rpsIdOld = oldMapPropertyInvoice.get( piObj.Id ).Rehab_Projected_Spend__c;
						if( rpsIdOld != null ) {
							setRehabProjectedSpendIds.add( rpsIdOld );
						}
					}
					setRehabProjectedSpendIds.add(piObj.Rehab_Projected_Spend__c);

			   }
		}

    	Map<Id, Rehab_Projected_Spend__c> mapRehabProjectedSpends = new Map<Id, Rehab_Projected_Spend__c>(
    	                                                                                                   [Select Id,
    	                                                                                                   		   Actual_Spend_Total__c,
    	                                                                                                   		   Changes_To_Budget__c,
    	                                                                                                   		   Base_Budget_Amount__c,
    	                                                                                                   		   Base_Budget_Reported_Timestamp__c,
    	                                                                                                   		   Running_Total__c,
																											 	   Rehab__c,
																										           GL_Code_Original__c,
																										           Rehab__r.Actual_Spend_Total__c,
																										           Rehab__r.Projected_Spend_Running_Total__c,
																										           Rehab__r.Projected_Spend_Changes_To_Budget__c
																										    From Rehab_Projected_Spend__c
																										    Where Id in: setRehabProjectedSpendIds
																										   ]
    																									  );

		Map<Id, Rehab__c> mapRehabsToUpdate = new map<Id, Rehab__c>();

    	for( Property_Invoice__c piObj : newPropertyInvoice ) {

				if( piObj.Rehab_Projected_Spend__c != null
						  &&
						  	(   Utility.hasFieldChanged( piObj, oldMapPropertyInvoice, 'Invoice_Amount__c')
						  	 || Utility.hasFieldChanged( piObj, oldMapPropertyInvoice, 'Rehab_Projected_Spend__c')) ) {

					if( mapRehabProjectedSpends.containsKey( piObj.Rehab_Projected_Spend__c ) ) {

						Rehab_Projected_Spend__c rpsObj = mapRehabProjectedSpends.get( piObj.Rehab_Projected_Spend__c );
						Rehab__c rehab;

						if( !mapRehabsToUpdate.containsKey( rpsObj.Rehab__c ) ) {
							rehab = new Rehab__c( Id = rpsObj.Rehab__c,
												  Actual_Spend_Total__c = ( rpsObj.Rehab__r.Actual_Spend_Total__c == null ? 0 : rpsObj.Rehab__r.Actual_Spend_Total__c )
												);
						}
						else {
							rehab = mapRehabsToUpdate.get( rpsObj.Rehab__c );
						}

						Decimal invoiceAmount = returnZeroIfInputNull( piObj.Invoice_Amount__c );

						if( trigger.isInsert ) {

							Decimal actualSpendTotal = returnZeroIfInputNull( rpsObj.Actual_Spend_Total__c );
							rpsObj.Actual_Spend_Total__c = actualSpendTotal + invoiceAmount;

							rehab.Actual_Spend_Total__c = returnZeroIfInputNull( rehab.Actual_Spend_Total__c )
																	 + returnZeroIfInputNull( invoiceAmount );

						}
						if( trigger.isUpdate ) {
							Decimal invoiceAmountOld = returnZeroIfInputNull( oldMapPropertyInvoice.get( piObj.Id ).Invoice_Amount__c );

							//if reference Rehab_Projected_Spend__c is changed
							if( Utility.hasFieldChanged( piObj, oldMapPropertyInvoice, 'Rehab_Projected_Spend__c') ) {

								Id rpsIdOld = oldMapPropertyInvoice.get( piObj.Id ).Rehab_Projected_Spend__c;

								if( rpsIdOld != null && mapRehabProjectedSpends.containsKey( rpsIdOld ) ) {

									Rehab_Projected_Spend__c rpsObjOldConnected = mapRehabProjectedSpends.get( rpsIdOld );

									Decimal actualSpendTotal = returnZeroIfInputNull( rpsObjOldConnected.Actual_Spend_Total__c );
									rpsObjOldConnected.Actual_Spend_Total__c = actualSpendTotal - invoiceAmount;
								}

								Decimal actualSpendTotal = returnZeroIfInputNull( rpsObj.Actual_Spend_Total__c );
								rpsObj.Actual_Spend_Total__c = actualSpendTotal + invoiceAmount;

							}
							else {

									Decimal actualSpendTotal = returnZeroIfInputNull( rpsObj.Actual_Spend_Total__c );
									rpsObj.Actual_Spend_Total__c = actualSpendTotal + invoiceAmount - invoiceAmountOld;
							}

							/*
							rehab.Actual_Spend_Total__c = returnZeroIfInputNull( rehab.Actual_Spend_Total__c )
																 + returnZeroIfInputNull( invoiceAmount ) - invoiceAmountOld;
							*/

						}

						//mapRehabsToUpdate.put( rpsObj.Rehab__c, rehab );

					}
			   }
		}

		if( mapRehabProjectedSpends.size() > 0 ) {
			update mapRehabProjectedSpends.values();
		}
		/*
		if( mapRehabsToUpdate.size() > 0 ) {
			update mapRehabsToUpdate.values();
		}
		*/
	}

	private static Decimal returnZeroIfInputNull( Decimal inputVal ) {
    	return ( inputVal == null ? 0 : inputVal );
    }
}