mdapi/Custom/objects/GL_Code__c.object
<CustomObject>
    <fields>
        <fullName>GL_Code_Acquisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code Acquisition</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>GL Codes (GL Code Acquisition)</relationshipLabel>
        <relationshipName>GL_Codes_Acquisition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Turn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code Turn</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>GL Codes (GL Code Turn)</relationshipLabel>
        <relationshipName>GL_Codes_Turn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/HD_Budget_Walk__c.object
<CustomObject>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab ID</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipName>HD_Budget_Walks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Budget Walk Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Acquisitions</fullName>
                </value>
                <value>
                    <fullName>Post-Acquisitions</fullName>
                </value>
                <value>
                    <fullName>Turn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HD Budget Walk</label>
    <nameField>
        <displayFormat>BW-{000000}</displayFormat>
        <label>HD Budget Walk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HD Budget Walks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab__c.object
<CustomObject>
    <description>This is the central record for the Rehab deployment.  Tracks all key details relating to the Rehab process.</description>
    <fields>
        <fullName>HD_Budget_Walk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HD Budget Walk</label>
        <referenceTo>HD_Budget_Walk__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Post Acquisition – Purchased Rented</fullName>
                </value>
                <value>
                    <fullName>Post-Acquisition</fullName>
                </value>
                <value>
                    <fullName>Turn</fullName>
                </value>
                <value>
                    <fullName>Remediation</fullName>
                </value>
                <value>
                    <fullName>Disposition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rehab</label>
    <nameField>
        <displayFormat>RHB-{0000}</displayFormat>
        <label>Rehab Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/classes/GL_Code_Service.cls
/**
 *   Description  :  Controller Class for VFP RehabProjectedSpend
 *
 *   Created By Shrinath
 *
 *   Created Date:  02/02/2014
 *
 *   Revision Logs:  V1.0 - Created
 **/
 public without sharing class GL_Code_Service {

	private static Map<Id, RecordType> mapRehabRecordType;

	// method to get type adjusted GL Code from Associated Rehab
	public Static String getTypeAdjustedGLCode( GL_Code__c glCodeObj, Rehab__c rehabObj ) {

		if( mapRehabRecordType == null ) {
			mapRehabRecordType = new Map<Id, RecordType>( [Select Id, Name
															  From RecordType
														   Where SObjectType = 'Rehab__c']
														  );
		}

		String recordTypeName = rehabObj.RecordType.Name;
		if( recordTypeName == null && rehabObj.RecordTypeId != null && mapRehabRecordType.containsKey( rehabObj.RecordTypeId )) {
		 	recordTypeName = mapRehabRecordType.get( rehabObj.RecordTypeId ).Name;
		}

		if( recordTypeName != null && recordTypeName == 'Post-Acquisition' ) {
			return  ( glCodeObj.GL_Code_Acquisition__c != null && glCodeObj.GL_Code_Acquisition__r.Name != null ) ? glCodeObj.GL_Code_Acquisition__r.Name : glCodeObj.Name;
		}
		else {
			return ( glCodeObj.GL_Code_Turn__c != null && glCodeObj.GL_Code_Turn__r.Name != null ) ? glCodeObj.GL_Code_Turn__r.Name : glCodeObj.Name;
		}
	}

	// method to get type adjusted GL Code from Associated HD Budget Walk
	public Static String getTypeAdjustedGLCode( GL_Code__c glCodeObj, HD_Budget_Walk__c hdBudgetWalkObj ) {

		if( hdBudgetWalkObj.Type__c != null && hdBudgetWalkObj.Type__c.containsIgnoreCase( 'Acquisition' )) {
			return  ( glCodeObj.GL_Code_Acquisition__c != null && glCodeObj.GL_Code_Acquisition__r.Name != null ) ? glCodeObj.GL_Code_Acquisition__r.Name : glCodeObj.Name;
		}
		else {
			return ( glCodeObj.GL_Code_Turn__c != null && glCodeObj.GL_Code_Turn__r.Name != null ) ? glCodeObj.GL_Code_Turn__r.Name : glCodeObj.Name;
		}
	}
}