mdapi/Custom/objects/HOA_Payments__c.object
<CustomObject>
    <description>This is part of the HOA application and can be used to generate the spreadsheet to request HOA payments from corporate accounting.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HOA_Tracker__c</fullName>
        <label>HOA Tracker</label>
        <referenceTo>HOA_Tracking__c</referenceTo>
        <relationshipName>HOA_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HOA Dues Payment</label>
    <nameField>
        <displayFormat>HOADuesPayment-{0000}</displayFormat>
        <label>HOA Dues Payment Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HOA Dues Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/HOA_Tracking__c.object
<CustomObject>
    <description>This is part of the HOA application.  This is a joiner object that connects the HOA company record to the related Portfolio record and houses property specific details such as HOA Account Number and workflow to ensure all steps are taken upon acquisition.  (Confirming receipt of CCRs, etc.)</description>
    <fields>
        <fullName>Most_Recent_HOA_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Most Recent HOA Payments</description>
        <label>Most Recent HOA Payment</label>
        <referenceTo>HOA_Payments__c</referenceTo>
        <relationshipLabel>HOA Tracking</relationshipLabel>
        <relationshipName>HOA_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HOA Tracking</label>
    <nameField>
        <displayFormat>HOA Tracking-{0000}</displayFormat>
        <label>HOA Tracking #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HOA Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/classes/HOAPaymentsTriggerHelper.cls
/**
 *   Description	:	Helper class to perform pre and post operations on HOA payments records.
 *
 *   Created By   	:	Bhavi Sharma
 *
 *   Created Date 	:	02/20/2014
 *
 *   Revision Logs	:	V_1.0 - Created
 *
 **/
public class HOAPaymentsTriggerHelper {

	/**
     *  @description    :   Method to set Most Recent HOA Due Payment lookup field on "HOA Tracking" object with most recent HOA Payments record.
     *
     *  @args           :   List of new HOA Payments, Map of old HOA Payments
     *
     *  @return         :   void
     *
     **/
    public static void populateMostRecentHOAPayment(List<HOA_Payments__c> newHOAPayments, Map<Id, HOA_Payments__c> mapOldHOAPayments) {

		//Set to hold Parent HOA Tracking Ids
        Set<Id> setHOATrackingIds = new Set<Id>();

	    //List to hold the current Context HOA_Payments__c
	    List<HOA_Payments__c> listHOAPayments = newHOAPayments != null ? newHOAPayments : mapOldHOAPayments.values();

	    //Loop through the records list and populate the setClaimIds
	    for(HOA_Payments__c hP : listHOAPayments) {

	    	//If trigger is executing in case of update, Check old and new value before executing the login
	    	//Run always for insert and delete
	    	if((newHOAPayments != null && mapOldHOAPayments != null && hP.Due_Date__c != mapOldHOAPayments.get(hP.Id).Due_Date__c)
	    			|| (newHOAPayments != null && mapOldHOAPayments == null && hP.Due_Date__c != null)
	    			|| (newHOAPayments == null && mapOldHOAPayments != null && hP.Due_Date__c != null)) {

	    		//This should be processed
	    		setHOATrackingIds.add(hP.HOA_Tracker__c);
	    	}
	    }

		//Chech set size before executing the query
		if(setHOATrackingIds.size() == 0)
			return;

	    //List to hold the "HOA Tracking" record to update
        List<HOA_Tracking__c> listHOATrackings = new List<HOA_Tracking__c>();

        //Populate Map to hold the Parent HOA Tracking record Id value as key and most recent HOA Payments record as value
        for(HOA_Tracking__c hTrack : [SELECT Id, Most_Recent_HOA_Payment__c,
        										(SELECT Id FROM HOA_Payments__r WHERE Due_Date__c != null ORDER BY Due_Date__c DESC LIMIT 1)
        										FROM HOA_Tracking__c WHERE Id IN : setHOATrackingIds] ) {

			//Only Process the record if found and
			if(hTrack.HOA_Payments__r.size() > 0 && hTrack.Most_Recent_HOA_Payment__c != hTrack.HOA_Payments__r[0].Id) {

				//Add record in the list to be updated
				hTrack.Most_Recent_HOA_Payment__c = hTrack.HOA_Payments__r[0].Id;
				listHOATrackings.add(hTrack);
			}
		}

        //Only update the records if there any
		if(listHOATrackings.size() > 0)
			update listHOATrackings;
	}
}