mdapi/Custom/objects/Listing__c.object
<CustomObject>
    <description>This is part of the Leasing/Marketing deployment.  Tracks all key details and workflow related to homes on the market.  There are Triggers between Listing and Application Tracking that update Status fields on both records.  Use SkipTriggersForUser when doing any data updates to Listing or Application Tracking.</description>
    <fields>
        <fullName>Portfolio__c</fullName>
        <label>Portfolio</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property__c.object
<CustomObject>
    <description>This is the output of the Acquisition reporting process and is the primary &quot;purchase record&quot; of all of our properties.</description>
    <fields>
        <fullName>Occupied_Status_Acquisition__c</fullName>
        <inlineHelpText>The following Status fields are dependent on this field: Post Acquisition Next Step, Rehab Status, Occupied Status @ Current</inlineHelpText>
        <label>Occupied Status @ Acquisition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Occupied</fullName>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Purchased Rented</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to track the rehab record related to the portfolio</description>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Portfolio</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Portfolio</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SWAY__c</fullName>
        <description>Checkbox is true when Market2 is in Dallas, Denver, Houston, and Nashville.</description>
        <formula>Residence__r.SWAY__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SWAY</label>
        <type>Checkbox</type>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab__c.object
<CustomObject>
    <description>This is the central record for the Rehab deployment.  Tracks all key details relating to the Rehab process.</description>
    <fields>
        <fullName>Home__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <label>Portfolio</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Rehabs</relationshipLabel>
        <relationshipName>Rehabs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Re_Key_Ready_Date__c</fullName>
        <label>Re-Key Ready Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Re_Key_Ready__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Re-Key Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>DO NOT MAKE ANY CHANGES TO THIS FIELD WITHOUT MAKING CORRESPONDING CHANGES TO REHAB STATUS FIELD.</description>
        <label>Rehab Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Notification Received</fullName>
                </value>
                <value>
                    <fullName>Ready to Schedule MOI/Utility Transfer</fullName>
                </value>
                <value>
                    <fullName>Move Out Scheduled</fullName>
                </value>
                <value>
                    <fullName>Move Out Assigned</fullName>
                </value>
                <value>
                    <fullName>Re-key Ready</fullName>
                    <default>true</default>
                    <label>Re-key Ready</label>
                </value>
                <value>
                    <fullName>Move Out Complete/Needs Final Budget</fullName>
                </value>
                <value>
                    <fullName>Sent to Locksmith</fullName>
                </value>
                <value>
                    <fullName>Re-key Complete</fullName>
                </value>
                <value>
                    <fullName>Budget/Depo Finalized/Needs Vendors</fullName>
                </value>
                <value>
                    <fullName>Front-End Assigned</fullName>
                </value>
                <value>
                    <fullName>Needs Final Budget</fullName>
                </value>
                <value>
                    <fullName>Needs Vendors</fullName>
                </value>
                <value>
                    <fullName>Needs GC</fullName>
                </value>
                <value>
                    <fullName>GC Awarded</fullName>
                </value>
                <value>
                    <fullName>2 Day Walk Complete</fullName>
                </value>
                <value>
                    <fullName>Five Day Complete</fullName>
                </value>
                <value>
                    <fullName>QC Assigned</fullName>
                </value>
                <value>
                    <fullName>QC Open</fullName>
                </value>
                <value>
                    <fullName>QC Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed - Completed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Rehab Needed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>HOLD - Personal Property</fullName>
                </value>
                <value>
                    <fullName>HOLD - Utilities</fullName>
                </value>
                <value>
                    <fullName>HOLD - BK</fullName>
                </value>
                <value>
                    <fullName>HOLD - Deed</fullName>
                </value>
                <value>
                    <fullName>HOLD - Occupied/TIP</fullName>
                </value>
                <value>
                    <fullName>HOLD - Other</fullName>
                </value>
                <value>
                    <fullName>HOLD - Permits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Post Acquisition – Purchased Rented</fullName>
                </value>
                <value>
                    <fullName>Post-Acquisition</fullName>
                </value>
                <value>
                    <fullName>Turn</fullName>
                </value>
                <value>
                    <fullName>Remediation</fullName>
                </value>
                <value>
                    <fullName>Disposition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rehab</label>
    <nameField>
        <displayFormat>RHB-{0000}</displayFormat>
        <label>Rehab Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehabs</pluralLabel>
    <recordTypes>
        <fullName>Post_Acquisition</fullName>
        <active>true</active>
        <label>Post-Acquisition</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Residence__c.object
<CustomObject>
    <description>This is the &quot;parent&quot; account of all Portfolio records and represents a property address.</description>
    <fields>
        <fullName>SWAY__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox is true when Market2 is in Dallas, Denver, Houston, and Nashville.</description>
        <label>SWAY</label>
        <type>Checkbox</type>
    </fields>
    <label>Residence</label>
    <nameField>
        <displayFormat>RES-{00000}</displayFormat>
        <label>Residence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/TIP_Tracking__c.object
<CustomObject>
    <description>This is the primary object in the TIP deployment.  Tracks status and workflow for all TIP properties.</description>
    <fields>
        <fullName>Portfolio__c</fullName>
        <label>Portfolio</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>TIPs</relationshipLabel>
        <relationshipName>TIPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Once you send click the &quot;Ready to Rekey&quot; button,  a rehab record will be created and will be linked here.  Conversely, if this property was originally sent to rehab and they sent it back to TIP, the original rehab record will be linked here.</inlineHelpText>
        <label>Rehab Record</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>TIPs</relationshipLabel>
        <relationshipName>Rehub_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence</label>
        <referenceTo>Residence__c</referenceTo>
        <relationshipLabel>TIPs</relationshipLabel>
        <relationshipName>TIPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TIP</label>
    <nameField>
        <displayFormat>TIP-{0000}</displayFormat>
        <label>TIP Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TIPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Custom--app/main/default/classes/PortfolioManagement.cls
/**
    * Apex Class: PortfolioManagement
    * Description:
    * Created By: Sudhir Kr. Jagetiya
    * Created Date: March 20, 2013
    * Last Modified By: Barkha Jain
    * Modified Date: March 28, 2013
    */
public without sharing class PortfolioManagement {

    /*
    static final String PORTFOLIO_OCCUPIED_STATUS_ACQUISITION_VACANT = 'Vacant';
    public static void afterInsert(List<Property__c> newList) {
        createRehabAndListingRecords(newList);
    }
    private static void createRehabAndListingRecords(List<Property__c> newList) {
        Map<Id, Rehab__c> portfolioRehabMap = new Map<Id, Rehab__c>();
        List<Listing__c> listingRecords = new List<Listing__c>();
        List<TIP_Tracking__c> reordListTIP = new List<TIP_Tracking__c>();

        for(Property__c portfolio : newList) {
            if(portfolio.Occupied_Status_Acquisition__c != null &&
                    portfolio.Occupied_Status_Acquisition__c.equalsIgnoreCase(PORTFOLIO_OCCUPIED_STATUS_ACQUISITION_VACANT)) {
                if(portfolio.Residence__c != null) {
                    listingRecords.add(createListing(portfolio.Id, portfolio.Residence__c));
                    portfolioRehabMap.put(portfolio.Id, createRehab(portfolio.Id, portfolio.Residence__c));
                    //***4/5 jdauernheim(Appirio)
                    //since createRehab is called from somewhere else, setting stage here to not interfere with other code
                    For(String PortfolioKey : portfolioRehabMap.keyset()){
                        Rehab__c RehabRec = new Rehab__c();
                        RehabRec = portfolioRehabMap.get(PortfolioKey);
                        RehabRec.Stage__c = 'Re-key Ready';
                    }
                }
            } else {
                reordListTIP.add(createTIP(portfolio.Id, portfolio.Residence__c));
            }
        }

        insert reordListTIP;
        insert portfolioRehabMap.values();

        for(Listing__c listing : listingRecords) {
            listing.Rehab__c = portfolioRehabMap.get(listing.Portfolio__c).Id;
        }
        insert listingRecords;
    }

    public static Rehab__c createRehab(Id portfolioId, Id homeId) {
        Rehab__c rehabRec = new Rehab__c();
        rehabRec.Portfolio__c = portfolioId;
        rehabRec.Home__c = homeId;
      //  rehabRec.Re_Key_Ready__c = true;        //4-5 JD(appirio) per issue documented, this field should not be set & will be removed from object.
        rehabRec.Re_Key_Ready_Date__c = system.Today();
        rehabRec.Stage__c = 'New';
        //@Barkha: T-127726
        rehabRec.Type__c = 'Post-Acquisition';
        return rehabRec;
    }

    public static Listing__c createListing(Id portfolioId, Id homeId) {
        Listing__c listingRec = new Listing__c();
        listingRec.Residence__c = homeId;
        listingRec.Portfolio__c = portfolioId;
        return listingRec;
    }

    private static TIP_Tracking__c createTIP(Id portfolioId, Id homeId) {
        TIP_Tracking__c tipTracking = new TIP_Tracking__c();
        tipTracking.Portfolio__c = portfolioId;
        tipTracking.Residence__c = homeId;
        return tipTracking;
    }
    */

    /* SIR - D-00004782 Code needed to auto create Listing records */
    public static final String PORTFOLIO_OCCUPIED_STATUS_ACQUISITION_VACANT = 'Vacant';

    public static final String REHAB_STAGE_RE_KEY_READY = 'Re-key Ready';

    public static void createRehabAndListingRecords(List<Property__c> newList) {
        Map<Id, Rehab__c> portfolioRehabMap = new Map<Id, Rehab__c>();
        List<Listing__c> listingRecords = new List<Listing__c>();
        List<TIP_Tracking__c> reordListTIP = new List<TIP_Tracking__c>();

        RecordType postAcquisitionRT = [Select Id from RecordType Where SObjectType = 'Rehab__c' And DeveloperName = 'Post_Acquisition' ];

        for(Property__c portfolio : newList) {
        
            //Added by Poonam Bhargava - (D-00017506) - bypass logic for SWAY Market
            if(portfolio.Occupied_Status_Acquisition__c != null &&
                    portfolio.Occupied_Status_Acquisition__c.equalsIgnoreCase(PORTFOLIO_OCCUPIED_STATUS_ACQUISITION_VACANT) && !portfolio.SWAY__c) {
                    if(portfolio.Residence__c != null) {
                        listingRecords.add(createListing(portfolio.Id, portfolio.Residence__c));
                        Rehab__c RehabRec = createRehab(portfolio.Id, portfolio.Residence__c, postAcquisitionRT.Id);
                        RehabRec.Stage__c = REHAB_STAGE_RE_KEY_READY;
                        portfolioRehabMap.put(portfolio.Id, RehabRec);
                    }
			}else {
                    reordListTIP.add(createTIP(portfolio.Id, portfolio.Residence__c));
            }  
        }

        insert reordListTIP;
        insert portfolioRehabMap.values();

        for(Listing__c listing : listingRecords) {
            listing.Rehab__c = portfolioRehabMap.get(listing.Portfolio__c).Id;
        }

        insert listingRecords;

    }

    public static Rehab__c createRehab(Id portfolioId, Id homeId, Id recordTypeId) {
        Rehab__c rehabRec = new Rehab__c();
        rehabRec.Portfolio__c = portfolioId;
        rehabRec.Home__c = homeId;
        rehabRec.Re_Key_Ready_Date__c = system.Today();
        rehabRec.Stage__c = 'New';
        rehabRec.RecordTypeId = recordTypeId;
        return rehabRec;
    }

    public static Listing__c createListing(Id portfolioId, Id homeId) {
        Listing__c listingRec = new Listing__c();
        listingRec.Residence__c = homeId;
        listingRec.Portfolio__c = portfolioId;
        return listingRec;
    }

    private static TIP_Tracking__c createTIP(Id portfolioId, Id homeId) {
        TIP_Tracking__c tipTracking = new TIP_Tracking__c();
        tipTracking.Portfolio__c = portfolioId;
        tipTracking.Residence__c = homeId;
        return tipTracking;
    }
}