mdapi/Custom/objects/Property_Invoice__c.object
<CustomObject>
    <description>Deployed Via Permission Set.This is a holding place to support a future state w/ rehab actuals/invoices.</description>
    <fields>
        <fullName>Approved_By__c</fullName>
        <formula>Case (Rehab__r.Region__c ,

&quot;Atlanta&quot;,&quot;James Turner&quot;, 
&quot;Charlotte&quot;,&quot;Doug Mann&quot;, 
&quot;Chicago&quot;,IF( Rehab__r.Property_State__c = &quot;MN&quot;, &quot;Greg Halleland&quot;, &quot;Bryan Henson&quot;), 
&quot;Inland Empire&quot;,&quot;Jay Skjevren&quot;, 
&quot;Jacksonville&quot;,&quot;Ken Mitchell&quot;, 
&quot;Las Vegas&quot;,&quot;Michael Murphy&quot;, 
&quot;Los Angeles&quot;,&quot;George Bishop&quot;, 
&quot;Miami&quot;,&quot;Doug Wilson&quot;, 
&quot;Orlando&quot;,&quot;William Redding&quot;, 
&quot;Phoenix&quot;,&quot;Steve Letcher&quot;, 
&quot;Sacramento&quot;,&quot;Scotte Henderson&quot;, 
&quot;Seattle&quot;,&quot;Jeff Taylor&quot;, 
&quot;Tampa&quot;,&quot;Alexis Antoni&quot;,Null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approved By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Submitted_to_Yardi__c</fullName>
        <description>Date this was sent in a batch to Yardi</description>
        <label>Date Submitted to Yardi</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GL_Code_Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Type_Adjusted__c</fullName>
        <formula>IF( ISPICKVAL( Rehab__r.Type__c, &apos;Post-Acquisition&apos; ), 
IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
, GL_Code_Original__r.Name, 
GL_Code_Original__r.GL_Code_Acquisition__r.Name 
), 
IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
GL_Code_Original__r.Name, 
GL_Code_Original__r.GL_Code_Turn__r.Name 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GL Code Type Adjusted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Include_in_Yardi_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if you would like this invoice included in the next batch upload</description>
        <inlineHelpText>Check this box if you would like this invoice included in the next batch upload</inlineHelpText>
        <label>Include in Yardi Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Month__c</fullName>
        <formula>TEXT(Month( Date_Paid__c))&amp;&quot;-&quot;&amp; TEXT(YEAR(Date_Paid__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Post Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rehab_Projected_Spend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab Projected Spend</label>
        <referenceTo>Rehab_Projected_Spend__c</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Remarks_Appears_on_GL__c</fullName>
        <formula>Notes_Print_on_Check_Stub__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remarks (Appears on GL)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Check_to__c</fullName>
        <label>Return Check to</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Region Office</fullName>
                    <default>true</default>
                    <label>Region Office</label>
                </value>
                <value>
                    <fullName>Send to Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tran__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Tran #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>&quot;I&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>Vendor__r.Yardi_vendor_code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Property Invoices</relationshipLabel>
        <relationshipName>Property_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Yardi_Code__c</fullName>
        <formula>Rehab__r.Yardi_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Yardi Code</label>
        <type>Text</type>
    </fields>
    <label>Property Invoice</label>
    <nameField>
        <displayFormat>PropInvoice-{0000}</displayFormat>
        <label>Property Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab__c.object
<CustomObject>
    <description>This is the central record for the Rehab deployment.  Tracks all key details relating to the Rehab process.</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status is changed to Red or Yellow automatically based on estimated completion date.</inlineHelpText>
        <label>Delete_RYG Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                    <default>true</default>
                    <label>Green</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Post Acquisition – Purchased Rented</fullName>
                </value>
                <value>
                    <fullName>Post-Acquisition</fullName>
                </value>
                <value>
                    <fullName>Turn</fullName>
                </value>
                <value>
                    <fullName>Remediation</fullName>
                </value>
                <value>
                    <fullName>Disposition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yardi_Code__c</fullName>
        <formula>Portfolio__r.Yardi_Property_Code__c</formula>
        <label>Yardi Property Code</label>
        <type>Text</type>
    </fields>
    <label>Rehab</label>
    <nameField>
        <displayFormat>RHB-{0000}</displayFormat>
        <label>Rehab Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/objects/Rehab_Projected_Spend__c.object
<CustomObject>
    <fields>
        <fullName>GL_Code_Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Code</label>
        <referenceTo>GL_Code__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GL_Code_Type_Adjusted__c</fullName>
        <formula>IF( NOT(ISNULL(Rehab__c)) , 
      IF( ISPICKVAL( Rehab__r.Type__c, &apos;Post-Acquisition&apos; ), 
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
                      , GL_Code_Original__r.Name, 
                      GL_Code_Original__r.GL_Code_Acquisition__r.Name 
          ),
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
                      GL_Code_Original__r.Name,  
                      GL_Code_Original__r.GL_Code_Turn__r.Name ) 
        ),
      IF( OR( ISPICKVAL( HD_Budget_Walk__r.Type__c, &apos;Pre-Acquisitions&apos; ),
              ISPICKVAL( HD_Budget_Walk__r.Type__c, &apos;Post-Acquisitions&apos; ) ),   
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Acquisition__c ) 
                      , GL_Code_Original__r.Name, 
                      GL_Code_Original__r.GL_Code_Acquisition__r.Name 
          ),
          IF( ISBLANK( GL_Code_Original__r.GL_Code_Turn__c ) , 
                      GL_Code_Original__r.Name,  
                      GL_Code_Original__r.GL_Code_Turn__r.Name )
        )
    )</formula>
        <label>GL Code Type Adjusted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rehab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rehab</label>
        <referenceTo>Rehab__c</referenceTo>
        <relationshipLabel>Rehab Projected Spends</relationshipLabel>
        <relationshipName>Rehab_Projected_Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rehab Projected Spend</label>
    <nameField>
        <displayFormat>RPS-{00000000}</displayFormat>
        <label>RPS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rehab Projected Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Custom--app/main/default/classes/EmailPropertyInvoicesCSVController.cls
/**
 * 	Description		:	Controller class for EmailPropertyInvoicesCSV VF page.
 						This class is send the email to user with all All Invoices CSV where
 							Include_in_Yardi_Batch__c == true
 							Date_Submitted_to_Yardi__c == null
 							Status__c == 'Submitted'
  						Once the email is sent, Update the following fields of the queried records
  							Date_Submitted_to_Yardi__c = Today
  							Status__c = Paid
 *
 * 	Created By		:	Bhavi Sharma
 *
 * 	Created Date	:	11/21/2013
 *
 * 	Revision Logs	:	V_1.0 - Created
 *                      V_1.1 Shrinath : Made Without Sharing and D-00011329 ( Revision - BUG-4842 ) 02/05/2014
 *
 **/
public without sharing class EmailPropertyInvoicesCSVController {

	//Constructor
	public EmailPropertyInvoicesCSVController(ApexPages.StandardSetController controller) {

	}

	/**
	 * 	@description	:	This method is to query Property Invoices records which fit in the criteria
	 							Create a CSV and email to current user
	 							Update the fields of these records
	 *
	 * 	@args			:
	 *
	 * 	@return			:	void
	 *
	 **/
	public void emailCSVToUserAndUpdateInvoices() {

		//Create a savepoint to rollback the complete transaction in case of exception
		SavePoint sp = database.setSavePoint();

		try {

			//Query all the Invoices records
			List<Property_Invoice__c> propertyInvoices = [Select Type__c, Tran__c, Vendor_Code__c, Vendor__c, Vendor__r.Name, Invoice_Date__c, GL_Code_Original__c, GL_Code_Type_Adjusted__c, Post_Month__c,
																	Invoice_Number__c, Yardi_Code__c, Remarks_Appears_on_GL__c, Due_Date__c, Invoice_Amount__c,
																	Return_Check_to__c, Approved_By__c, Rehab_Projected_Spend__r.Name, Rehab__r.Name,
																	Comments__c, Include_in_Yardi_Batch__c, Rehab__c, Rehab_Projected_Spend__c
																	from Property_Invoice__c where Include_in_Yardi_Batch__c = true
																										AND Date_Submitted_to_Yardi__c = null
																										AND Status__c = 'Submitted'];
			//Display message if no records in CSV
			if(propertyInvoices.size() == 0) {

				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No records to email.'));
				return;
			}

			//Send email to user
			EmailPropertyInvoicesCSVController.EmailCSVToUser(propertyInvoices, 'Property Invoices.csv', 'Property Invoices');

			//Loop through all the records and update the invoices records
			for(Property_Invoice__c pInvoice : propertyInvoices) {

				pInvoice.Date_Submitted_to_Yardi__c = Date.today();
	  			pInvoice.Status__c = 'Paid';
			}

			//update pInvoice
			update propertyInvoices;

			//Add message on page
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Email sent successfully on ' + UserInfo.getUserEmail() + '.'));
		} catch(Exception e) {

			//Rollback the complete transaction
			database.rollBack(sp);

			//Add error on page
			ApexPages.addMessages(e);
		}
	}

	/**
	 * 	@description	:	This method is to process the Property invoices list
	 							Create a CSV and email to current user
	 							Update the fields of these records
	 *
	 * 	@args			:	List<Property_Invoice__c>
	 *
	 * 	@return			:	void
	 *
	 **/
	public static void EmailCSVToUser(List<Property_Invoice__c> propertyInvoices, String fileName, String subject) {

		//Properties
		String seperator = ',';
   		String newLine = '\n';

		//Header Row Content string
        String headerRow = 'Type,Tran #,Vendor Code,Vendor,Invoice Date,Post Month,Invoice Number,Comments,Yardi Code,Invoice Amount,GL Code,Remarks,Return Check to,Approved by';

        //Data row content string
        String dataRows = '';
        String dataRow = '';

        //Loop through existing property invoices records list
		for(Property_Invoice__c pInvoice : propertyInvoices) {

			//Populate data row content string with existing property invoices fields value
			dataRow = (newLine
									+ parseNull(pInvoice.Type__c)
									+ seperator + parseNull(pInvoice.Tran__c)
									+ seperator + parseNull(pInvoice.Vendor_Code__c )
									+ seperator + parseNull(pInvoice.Vendor__r.Name)
									+ seperator + parseNull(string.valueOf(pInvoice.Invoice_Date__c))
									+ seperator + parseNull(pInvoice.Post_Month__c )
									+ seperator + parseNull(pInvoice.Invoice_Number__c)
									+ seperator + parseNull(pInvoice.Comments__c)
									+ seperator + parseNull(pInvoice.Yardi_Code__c)
									+ seperator + parseNull(pInvoice.Invoice_Amount__c)
									+ seperator + parseNull(pInvoice.GL_Code_Type_Adjusted__c)
									+ seperator + parseNull(pInvoice.Remarks_Appears_on_GL__c)
									+ seperator + parseNull(pInvoice.Return_Check_to__c)
									+ seperator + parseNull(pInvoice.Approved_By__c)
                                );

            //Appending row in the data rows string
   			dataRows += dataRow;
		}

		//Appending header row into the data rows
		dataRows = headerRow + dataRows;

		//Email Attachments List
		List<Messaging.EmailFileAttachment> emailAttachments = new List<Messaging.EmailFileAttachment>();

		//Email Attachment for property invoice records csv
		Messaging.EmailFileAttachment emailCSVAttachment = new Messaging.EmailFileAttachment();
		emailCSVAttachment.setFileName(fileName);
		emailCSVAttachment.setBody(Blob.valueOf(dataRows));

		//Adding attachment record into the list
		emailAttachments.add(emailCSVAttachment);

		//Email Message Instahce
		Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

		//Set attributes
		email.setSubject(subject);
     	email.setPlainTextBody('Please find the attached Property Invoices CSV.');
     	email.setFileAttachments(emailAttachments);
     	email.setToAddresses(new List<String>{UserInfo.getUserEmail()});
		Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
	}

	/**
	 * 	@description	:	Method to return blank string if value is null.
	 *
	 * 	@args			:	Object val
	 *
	 * 	@return			:	String
	 *
	 **/
     private static String parseNull(Object val) {
     	return (val == null ? '' : String.valueOf(val).escapeCSV());
     }
}