mdapi/Custom/objects/Property_Issue_Photo__c.object
<CustomObject>
    <fields>
        <fullName>Property_Issue__c</fullName>
        <label>Property Issue</label>
        <referenceTo>Property_Issues__c</referenceTo>
        <relationshipLabel>Property Issue Photos</relationshipLabel>
        <relationshipName>Property_Issue_Photos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>S3_Bucket__c</fullName>
        <label>S3 Bucket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Image_URL__c</fullName>
        <formula>&apos;https://&apos;+ S3_Bucket__c + &apos;.s3.amazonaws.com/&apos;+ S3_Path__c +&apos;?AWSAccessKeyId=&apos;+$Label.Access_Key_ID</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>S3 Image URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Path__c</fullName>
        <label>S3 Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Property Assessment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property Issue Photo</label>
    <nameField>
        <displayFormat>Photo-{000000}</displayFormat>
        <label>Property Issue Photo ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Issue Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/Custom/classes/S3PropertyIssueImagesController.cls
public without sharing class S3PropertyIssueImagesController
{
    public Sobject sObj {get;set;}
    public String pageTitle {get;set;}
    public List<String> ImageURLs {get;set;}

    public List<Property_Issue_Photo__c> lstPIImages {get;set;}
       
    public S3PropertyIssueImagesController(ApexPages.StandardController controller) 
    {
        try
        {
            sObj = controller.getRecord();
            lstPIImages = new List<Property_Issue_Photo__c>();
            pageTitle = '';
            ImageURLs = new List<String>();
            
            lstPIImages = [Select id, name, S3_Bucket__c, S3_Path__c, S3_Image_URL__c, Type__c, Property_Issue__c from Property_Issue_Photo__c where Property_Issue__c =: sObj.id ];
                
        }
        catch(Exception e)
        {
            ApexPages.addMessages(e);
        }
    }
}