mdapi/Custom/objects/Property__c.object
<CustomObject>
    <description>This is the output of the Acquisition reporting process and is the primary &quot;purchase record&quot; of all of our properties.</description>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <formula>Residence__r.Address_Zip_Code__c</formula>
        <label>Property Zip Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>This field maps to the Market2 value in the Yardi Integration file, &quot;AttributesMarket&quot;.  The similar Market field is derived via a Custom Setting called Yardi Short Region Config.</description>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Portfolio</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property_Issues__c.object
<CustomObject>
    <description>This is a object that can be used for the field to define any issues (things that are so disparate we couldn&apos;t possibly list them all in a picklist) and assign a person responsible to address the problem.  We have opted for this object instead of tasks as it provides easier reporting and visibility on the parent object (portfolio.)</description>
    <fields>
        <fullName>Postal_Code_Web_Submission__c</fullName>
        <label>Postal Code (Web Submission)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF(NOT(ISBLANK( Residence__c )) , TEXT(Residence__r.Region__c), 
IF(NOT(ISBLANK( Pipeline__c )) , TEXT(Pipeline__r.Region__c) , 
IF(NOT(ISBLANK( Portfolio__c )) , TEXT(Portfolio__r.Region__c) , 
IF( Web_Submission__c = TRUE, TEXT(What_Region_does_issue_Impact__c) , 
null ))))</formula>
        <label>Market2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Web_Submission__c</fullName>
        <label>State (Web Submission)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>California - Los Angeles Area</fullName>
                </value>
                <value>
                    <fullName>California - Inland Empire Area</fullName>
                </value>
                <value>
                    <fullName>California - Northern</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida - Northern</fullName>
                </value>
                <value>
                    <fullName>Florida - Orlando Area</fullName>
                </value>
                <value>
                    <fullName>Florida - Tampa Area</fullName>
                </value>
                <value>
                    <fullName>Florida - Southern</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Web_Submission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Web Submission</label>
        <type>Checkbox</type>
    </fields>
    <label>Property Issue</label>
    <nameField>
        <displayFormat>Issue-{0000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Issues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/Custom/objects/Property_Opportunity__c.object
<CustomObject>
    <description>This is part of the Acquisitions deployment.  This object captures properties that have been placed into escrow and where the Approval process occurs that facilitates reporting and creation of Portfolio.</description>
    <fields>
        <fullName>Property_Zip_Code__c</fullName>
        <formula>Residence__r.Address_Zip_Code__c</formula>
        <label>*Property Zip Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/Custom/objects/Region_To_State_Web_Submission_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Region To State Web Submission Mapping</label>
    <pluralLabel>Region To State Web Submission Mappings</pluralLabel>
</CustomObject>

mdapi/Custom/objects/Residence__c.object
<CustomObject>
    <description>This is the &quot;parent&quot; account of all Portfolio records and represents a property address.</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Residence</label>
    <nameField>
        <displayFormat>RES-{00000}</displayFormat>
        <label>Residence Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/Custom/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Inland Empire</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/Custom/classes/Property_IssuesTriggerHelper.cls
/**
 *  Description :   Helper class for property issues trigger.
 *
 *  Created By  :   Shirnath 
 *
 *  Created Date:   01/12/2016
 *
 *  Revision Logs:  V1.0 - Created
 *					V1.1 - Modified By Poonam Bharagav - (D-00017166)
 *  Code Coverage - 100%
 **/
 public without sharing class Property_IssuesTriggerHelper {

    //This flag is to control the execution of Property Trigger
    public static Boolean EXECUTE_PROPERTY_TRIGGER = true;
     
    public static void setPropertyIssueWhatRegion(List<Property_Issues__c> propertyIssues) {
        
        // when current user is Formstack API user
        if( Userinfo.getUserName().equalsIgnoreCase( Label.Username_For_Formstack_ApiUser ) || Test.isrunningTest()) {
            
            List<Property_Issues__c> listAllowedPropertyIssues = new List<Property_Issues__c>();
            Set<String> setZipCodes = new Set<String>(); 
            for( Property_Issues__c pi : propertyIssues ) {
                if( pi.Postal_Code_Web_Submission__c != null ) {
                    
                        listAllowedPropertyIssues.add( pi );
                        setZipCodes.add( pi.Postal_Code_Web_Submission__c );
                    
                }
            }
            
            if( setZipCodes.size() > 0 ) {
                Map<Id, Property__c> mapProperty = new Map<Id, Property__c>( [ Select Region__c, Property_Zip_Code__c
                                                                               From Property__c
                                                                               Where Property_Zip_Code__c in: setZipCodes   
                                                                              ]);
                
                Map<String, String> mapZipcodeToRegion = new Map<String, String>();
                for( Property__c propertyObj : mapProperty.values()) {
                    mapZipcodeToRegion.put( propertyObj.Property_Zip_Code__c, propertyObj.Region__c );
                }
                
                Map<String, String> mapRegionToStateWebSubmission = new Map<String, String>();
                
                // loop over custom metadata for Region State Web Submission Mappings
                for( Region_To_State_Web_Submission_Mapping__mdt objRegionSWSMapping : [ Select Region__c, 
                                                                                            State_Web_Submission__c
                                                                                        From Region_To_State_Web_Submission_Mapping__mdt
                                                                                        Where Region__c !=: NULL 
                                                                                        AND State_Web_Submission__c !=: NULL] ) {
                                                                                        
                    mapRegionToStateWebSubmission.put( objRegionSWSMapping.Region__c.trim().toLowerCase(), objRegionSWSMapping.State_Web_Submission__c );
                }
                
                // loop over property issues
                for( Property_Issues__c pi : listAllowedPropertyIssues ) {
                    // when mapZipcodeToRegion has value for the zipcode
                    if( mapZipcodeToRegion.containsKey( pi.Postal_Code_Web_Submission__c )) {
                        String regionForZipcode = mapZipcodeToRegion.get( pi.Postal_Code_Web_Submission__c );
                        // when region found from zip is not equals to What_Region_does_issue_Impact__c 
                        if( regionForZipcode != null && pi.What_Region_does_issue_Impact__c != regionForZipcode ) {
                            // when mapRegionToStateWebSubmission has value for the region
                            if( mapRegionToStateWebSubmission.containsKey( regionForZipcode.trim().toLowerCase() )) {
                                String stateWebSubmission = mapRegionToStateWebSubmission.get( regionForZipcode.trim().toLowerCase() ); 
                                if( stateWebSubmission != null ) {
                                    pi.State_Web_Submission__c = stateWebSubmission;
                                    pi.What_Region_does_issue_Impact__c = regionForZipcode;
                                }
                            }
                        }
                    }
                }
            }
            
        }
    }
    
	//Added by Poonam Bhargava  - D-00017166
	/**
	*	@description	:	Method to populate 'Market' field on Property Issues from Residence/Pipeline/Portfolio's Market field
	*
	*	@arg			:	List<Property_Issues__c> propertyIssues, Map<Id, Property_Issues__c> mapOldIssues
	*
	*	@return			:	Void  
	**/
    public static void populateMarketfromPortfolio(List<Property_Issues__c> propertyIssues, Map<Id, Property_Issues__c> mapOldIssues){
    
    	//Set to hold Portfolio Ids
    	Set<Id> setOfPortfolioIds = new Set<Id>(); 
    	
    	//Set to hold Residence Ids
    	Set<Id> setOfResidenceIds = new Set<Id>();
    	
    	//Set to hold P Ids 
    	Set<Id> setOfPipelineIds = new Set<Id>(); 
    	
    	//Loop over trigger.new list	
    	for(Property_Issues__c pI : propertyIssues){
    	
    		//Check for null value in Region and Market field	
    		if(pI.Region__c != null && pI.Market__c == null){
    		
    			//Check for Residence null value and populate set accordingly with residence ids
    			if(pI.Residence__c  != null)
    				setOfResidenceIds.add(pI.Residence__c);
    			
    			//Check for Pipeline null value and populate set accordingly with Pipeline ids
	    		else if(pI.Pipeline__c  != null)
	    			setOfPipelineIds.add(pI.Pipeline__c);
	    		
	    		//Check for Portfolio null value and populate set accordingly with Portfolio ids	
	    		else if(pI.Portfolio__c != null)
	    			setOfPortfolioIds.add(pI.Portfolio__c);	
	    		
	    		//Check for web submission field value and populayte market accordingly]
	    		else if(pI.Web_Submission__c)
    				pI.Market__c = pI.What_Region_does_issue_Impact__c;	
    		}	
    	}
    	
    	//Map to hold Residence Id with Residence records
    	Map<Id, Residence__c> mapResidence;
    	
    	//Map to hold Portfolio Id with Portfolio Record
      	Map<Id, Property__c> mapPortfolio;
 
 		//Map to hold Pipeline Id with Pipeline records
     	Map<Id, Property_Opportunity__c> mapPipeline;
    	
    	//Check for setOfResidenceIds set size and populate map mapResidence accordingly 
    	if(setOfResidenceIds.size() > 0)
    			mapResidence = new Map<Id, Residence__c>([SELECT Id, Market__c FROM Residence__c WHERE Id IN: setOfResidenceIds]);
    			
    	//Check for setOfPipelineIds set size and populate map mapPipeline accordingly
    	if(setOfPipelineIds.size() > 0)
    			mapPipeline = new Map<Id, Property_Opportunity__c>([SELECT Id, Market__c FROM Property_Opportunity__c WHERE Id IN: setOfPipelineIds]);
    		
		//Check for setOfPortfolioIds set size and populate map mapPortfolio accordingly
    	if(setOfPortfolioIds.size() > 0)
    			mapPortfolio = new Map<Id, Property__c>([SELECT Id, Market__c FROM Property__c WHERE Id IN: setOfPortfolioIds]);
    	
    	//Loop over proeprty issue records	
    	for(Property_Issues__c pI : propertyIssues){
    		
    		//Check for null value in Region and Market field	
    		if(pI.Region__c != null && pI.Market__c == null){
    		
    			//Check for Residence null value and populate Market field on YRR accordingly
    			if(pI.Residence__c  != null && mapResidence != null && mapResidence.containsKey(pI.Residence__c))
    				pI.Market__c = mapResidence.get(pI.Residence__c).Market__c;
    			
    			//Check for Pipeline null value and populate Market field on YRR accordingly
	    		else if(pI.Pipeline__c  != null && mapPipeline != null && mapPipeline.containsKey(pI.Pipeline__c))
	    			pI.Market__c = mapPipeline.get(pI.Pipeline__c).Market__c;
	    		
	    		//Check for Portfolio null value and populate Market field on YRR accordingly	
	    		else if(pI.Portfolio__c != null && mapPortfolio != null && mapPortfolio.containsKey(pI.Portfolio__c))
	    			pI.Market__c = mapPortfolio.get(pI.Portfolio__c).Market__c;	
    		}	
    	}
    }
}